import Foundation

// Chantier structuration i18n du dosage (party 2026-06-14, Lot 1 yoga) — migration T3 (zéro dette).
//
// FICHIER GÉNÉRÉ depuis la table d'injection Python des templates yoga (source figée unique).
// NE PAS éditer à la main. Le filet `LegacyDoseMigrationTests` vérifie qu'il couvre exactement
// les mêmes strings que les templates bundlés.
//
// Rôle : reconstruire un `Dose` structuré depuis les strings legacy FR `duration`/`reps` des
// exercices PERSISTÉS avant le chantier (blob `AdaptedExercise` sans champ `dose`). Appliqué en
// FALLBACK display-time (`AdaptedExercise.effectiveDose`) — pas d'écriture SwiftData, pas de
// matching séance↔template, pas d'async. Le contenu NEUF porte déjà son `dose` (option A).
public enum LegacyDoseMigration {

    /// `Dose` reconstruit depuis les strings legacy (priorité `duration`, sinon `reps`).
    /// nil = string non reconnue → l'appelant garde le rendu legacy verbatim.
    public static func dose(duration: String?, reps: String?) -> Dose? {
        guard let key = duration ?? reps else { return nil }
        return table[key]
    }

    /// Toutes les clés FR couvertes (pour le filet de cohérence avec les templates).
    public static var coveredKeys: Set<String> { Set(table.keys) }

    static let table: [String: Dose] = [
        "1 cycle": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "cycles")!)),
        "1 cycle complet": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "cycles")!)),
        "1 cycle breath-led": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "1 cycle = 9 respirations breath-led": .freeText(LocalizedText(fr: "1 cycle = 9 respirations au rythme du souffle", en: "1 cycle = 9 breath-led breaths", es: "1 ciclo = 9 respiraciones al ritmo de la respiración")),
        "1 cycle = 17 respirations breath-led": .freeText(LocalizedText(fr: "1 cycle = 17 respirations au rythme du souffle", en: "1 cycle = 17 breath-led breaths", es: "1 ciclo = 17 respiraciones al ritmo de la respiración")),
        "1 cycle complet (~1 min 30)": .freeText(LocalizedText(fr: "1 cycle complet (~1 min 30)", en: "1 full cycle (~1 min 30)", es: "1 ciclo completo (~1 min 30)")),
        "1 cycle complet (~2 min)": .freeText(LocalizedText(fr: "1 cycle complet (~2 min)", en: "1 full cycle (~2 min)", es: "1 ciclo completo (~2 min)")),
        "1 min": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "minutes")!)),
        "1 min 30": .freeText(LocalizedText(fr: "1 min 30", en: "1 min 30", es: "1 min 30")),
        "2 min": .structured(StructuredDose(value: "2", unit: DoseUnit(rawValue: "minutes")!)),
        "2.5 min séquence": .structured(StructuredDose(value: "2.5", unit: DoseUnit(rawValue: "minutes")!)),
        "3 min": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "minutes")!)),
        "3.5 min finishing": .structured(StructuredDose(value: "3.5", unit: DoseUnit(rawValue: "minutes")!)),
        "3.5 min séquence": .structured(StructuredDose(value: "3.5", unit: DoseUnit(rawValue: "minutes")!)),
        "4 min": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "minutes")!)),
        "4 min finishing cutback": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "minutes")!)),
        "4 min séquence": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "minutes")!)),
        "4.5 min finishing": .structured(StructuredDose(value: "4.5", unit: DoseUnit(rawValue: "minutes")!)),
        "5 min": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "minutes")!)),
        "5 min séquence": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "minutes")!)),
        "5.5 min séquence": .structured(StructuredDose(value: "5.5", unit: DoseUnit(rawValue: "minutes")!)),
        "5.5 min séquence finishing": .structured(StructuredDose(value: "5.5", unit: DoseUnit(rawValue: "minutes")!)),
        "6 min": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "minutes")!)),
        "6 min finishing": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "minutes")!)),
        "6 min séquence": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "minutes")!)),
        "6.5 min finishing": .structured(StructuredDose(value: "6.5", unit: DoseUnit(rawValue: "minutes")!)),
        "7 min": .structured(StructuredDose(value: "7", unit: DoseUnit(rawValue: "minutes")!)),
        "8 min": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "minutes")!)),
        "10 min": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "minutes")!)),
        "12 min": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "minutes")!)),
        "15 min": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "minutes")!)),
        "18 min": .structured(StructuredDose(value: "18", unit: DoseUnit(rawValue: "minutes")!)),
        "20 min": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "minutes")!)),
        "20 min lecture + réflexion": .freeText(LocalizedText(fr: "20 min de lecture + réflexion", en: "20 min reading + reflection", es: "20 min de lectura + reflexión")),
        "3 min (~10 cycles)": .freeText(LocalizedText(fr: "3 min (~10 cycles)", en: "3 min (~10 cycles)", es: "3 min (~10 ciclos)")),
        "3 min (~10 cycles respiratoires)": .freeText(LocalizedText(fr: "3 min (~10 cycles respiratoires)", en: "3 min (~10 breath cycles)", es: "3 min (~10 ciclos respiratorios)")),
        "5 min (2 min Dirgha + 3 min Ujjayi)": .freeText(LocalizedText(fr: "5 min (2 min Dirgha + 3 min Ujjayi)", en: "5 min (2 min Dirgha + 3 min Ujjayi)", es: "5 min (2 min Dirgha + 3 min Ujjayi)")),
        "5 min (3 min Dirgha + 2 min Ujjayi)": .freeText(LocalizedText(fr: "5 min (3 min Dirgha + 2 min Ujjayi)", en: "5 min (3 min Dirgha + 2 min Ujjayi)", es: "5 min (3 min Dirgha + 2 min Ujjayi)")),
        "6 min (3 min Dirgha + 3 min Ujjayi)": .freeText(LocalizedText(fr: "6 min (3 min Dirgha + 3 min Ujjayi)", en: "6 min (3 min Dirgha + 3 min Ujjayi)", es: "6 min (3 min Dirgha + 3 min Ujjayi)")),
        "20 sec": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "seconds")!)),
        "25 sec": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "seconds")!)),
        "30 sec": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!)),
        "30 sec hold": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!)),
        "35 sec": .structured(StructuredDose(value: "35", unit: DoseUnit(rawValue: "seconds")!)),
        "40 sec": .structured(StructuredDose(value: "40", unit: DoseUnit(rawValue: "seconds")!)),
        "45 sec": .structured(StructuredDose(value: "45", unit: DoseUnit(rawValue: "seconds")!)),
        "50 sec": .structured(StructuredDose(value: "50", unit: DoseUnit(rawValue: "seconds")!)),
        "60 sec": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "seconds")!)),
        "90 sec": .structured(StructuredDose(value: "90", unit: DoseUnit(rawValue: "seconds")!)),
        "30-45 sec": .structured(StructuredDose(value: "30-45", unit: DoseUnit(rawValue: "seconds")!)),
        "20 sec par côté": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "30 sec par côté": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "45 sec par côté": .structured(StructuredDose(value: "45", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "60 sec par côté": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "60s par côté": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "30 sec Ujjayi par côté": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "20-30s par essai": .structured(StructuredDose(value: "20-30", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perAttempt")!)),
        "30s par essai": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perAttempt")!)),
        "45s par essai": .structured(StructuredDose(value: "45", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perAttempt")!)),
        "60s par essai": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perAttempt")!)),
        "60 sec par posture par côté": .freeText(LocalizedText(fr: "60 s par posture et par côté", en: "60 s per pose and per side", es: "60 s por postura y por lado")),
        "60s tenue": .freeText(LocalizedText(fr: "60 s en tenue", en: "60 s hold", es: "60 s en mantenimiento")),
        "60s libre tenue": .freeText(LocalizedText(fr: "60 s, tenue libre", en: "60 s, free hold", es: "60 s, mantenimiento libre")),
        "90s libre tenue": .freeText(LocalizedText(fr: "90 s, tenue libre", en: "90 s, free hold", es: "90 s, mantenimiento libre")),
        "3-5 sec hold + descente contrôlée": .freeText(LocalizedText(fr: "3-5 s de tenue + descente contrôlée", en: "3-5 s hold + controlled lowering", es: "3-5 s de mantenimiento + descenso controlado")),
        "3 respirations": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "breaths")!)),
        "5 respirations": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!)),
        "8 respirations": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "breaths")!)),
        "9 respirations": .structured(StructuredDose(value: "9", unit: DoseUnit(rawValue: "breaths")!)),
        "17 respirations": .structured(StructuredDose(value: "17", unit: DoseUnit(rawValue: "breaths")!)),
        "9 respirations breath-led": .structured(StructuredDose(value: "9", unit: DoseUnit(rawValue: "breaths")!, style: DoseStyle(rawValue: "breathLed")!)),
        "17 respirations breath-led": .structured(StructuredDose(value: "17", unit: DoseUnit(rawValue: "breaths")!, style: DoseStyle(rawValue: "breathLed")!)),
        "5 respirations Ujjayi": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "8 respirations Ujjayi": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "breaths")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "10 respirations Ujjayi": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "breaths")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "5 respirations par côté": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "8 respirations par côté": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "10 respirations par côté": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "5 respirations Ujjayi par côté": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "8 respirations Ujjayi par côté": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "10 respirations Ujjayi par côté": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perSide")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "5 respirations par posture": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perPose")!)),
        "5 respirations Ujjayi par posture": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perPose")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "5 respirations par tenue": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perHold")!)),
        "5 respirations par variante": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perVariation")!)),
        "5 respirations chaque variante": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perVariation")!)),
        "5 respirations Ujjayi par variante": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perVariation")!, style: DoseStyle(rawValue: "ujjayi")!)),
        "5 respirations chaque": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perEach")!)),
        "5 respirations chacune": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "breaths")!, qualifier: DoseQualifier(rawValue: "perEach")!)),
        "5 respirations + 9 roulis": .freeText(LocalizedText(fr: "5 respirations + 9 roulis", en: "5 breaths + 9 rolls", es: "5 respiraciones + 9 balanceos")),
        "5 respirations + Lolasana entre": .freeText(LocalizedText(fr: "5 respirations + Lolasana entre chaque", en: "5 breaths + Lolasana in between", es: "5 respiraciones + Lolasana entre cada una")),
        "5 respirations Ujjayi par côté par variante": .freeText(LocalizedText(fr: "5 respirations Ujjayi par côté et par variante", en: "5 Ujjayi breaths per side and per variation", es: "5 respiraciones Ujjayi por lado y por variación")),
        "5 respirations Ujjayi par posture / par côté": .freeText(LocalizedText(fr: "5 respirations Ujjayi par posture et par côté", en: "5 Ujjayi breaths per pose and per side", es: "5 respiraciones Ujjayi por postura y por lado")),
        "5 respirations Ujjayi par posture, vinyasa entre côtés": .freeText(LocalizedText(fr: "5 respirations Ujjayi par posture, vinyasa entre les côtés", en: "5 Ujjayi breaths per pose, vinyasa between sides", es: "5 respiraciones Ujjayi por postura, vinyasa entre lados")),
        "5 respirations chaque par côté": .freeText(LocalizedText(fr: "5 respirations chacune, par côté", en: "5 breaths each, per side", es: "5 respiraciones cada una, por lado")),
        "5 respirations chaque posture par côté": .freeText(LocalizedText(fr: "5 respirations par posture et par côté", en: "5 breaths per pose and per side", es: "5 respiraciones por postura y por lado")),
        "5 respirations chaque variante (avant + côté + dehri)": .freeText(LocalizedText(fr: "5 respirations par variante (avant + côté + dehri)", en: "5 breaths per variation (front + side + dehri)", es: "5 respiraciones por variación (frente + lado + dehri)")),
        "5 respirations par côté pour A et B": .freeText(LocalizedText(fr: "5 respirations par côté pour A et B", en: "5 breaths per side for A and B", es: "5 respiraciones por lado para A y B")),
        "30 respirations rapides + 1 Dirgha lente": .freeText(LocalizedText(fr: "30 respirations rapides + 1 Dirgha lente", en: "30 fast breaths + 1 slow Dirgha", es: "30 respiraciones rápidas + 1 Dirgha lenta")),
        "30 respirations rapides + 1 Dirgha entre cycles": .freeText(LocalizedText(fr: "30 respirations rapides + 1 Dirgha entre les cycles", en: "30 fast breaths + 1 Dirgha between cycles", es: "30 respiraciones rápidas + 1 Dirgha entre ciclos")),
        "30 expulsions actives + inspiration passive": .freeText(LocalizedText(fr: "30 expulsions actives + inspiration passive", en: "30 active exhales + passive inhale", es: "30 exhalaciones activas + inhalación pasiva")),
        "2 cycles breath-led": .structured(StructuredDose(value: "2", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "3 cycles breath-led": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "3 cycles breath-led enchaînés": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "3 cycles complets breath-led": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "4 cycles breath-led": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "4 cycles breath-led enchaînés": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "5 cycles breath-led": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),
        "5 cycles breath-led enchaînés": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "cycles")!, style: DoseStyle(rawValue: "breathLed")!)),

        // ====================== LOT 2 — RUNNING (généré, ne pas éditer) ======================
        "14 min": .structured(StructuredDose(value: "14", unit: DoseUnit(rawValue: "minutes")!)),
        "22 min": .structured(StructuredDose(value: "22", unit: DoseUnit(rawValue: "minutes")!)),
        "25 min": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "minutes")!)),
        "30 min": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "minutes")!)),
        "35 min": .structured(StructuredDose(value: "35", unit: DoseUnit(rawValue: "minutes")!)),
        "40 min": .structured(StructuredDose(value: "40", unit: DoseUnit(rawValue: "minutes")!)),
        "42 min": .structured(StructuredDose(value: "42", unit: DoseUnit(rawValue: "minutes")!)),
        "50 min": .structured(StructuredDose(value: "50", unit: DoseUnit(rawValue: "minutes")!)),
        "53 min": .structured(StructuredDose(value: "53", unit: DoseUnit(rawValue: "minutes")!)),
        "55 min": .structured(StructuredDose(value: "55", unit: DoseUnit(rawValue: "minutes")!)),
        "60 min": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "minutes")!)),
        "65 min": .structured(StructuredDose(value: "65", unit: DoseUnit(rawValue: "minutes")!)),
        "70 min": .structured(StructuredDose(value: "70", unit: DoseUnit(rawValue: "minutes")!)),
        "75 min": .structured(StructuredDose(value: "75", unit: DoseUnit(rawValue: "minutes")!)),
        "78 min": .structured(StructuredDose(value: "78", unit: DoseUnit(rawValue: "minutes")!)),
        "82 min": .structured(StructuredDose(value: "82", unit: DoseUnit(rawValue: "minutes")!)),
        "92 min": .structured(StructuredDose(value: "92", unit: DoseUnit(rawValue: "minutes")!)),
        "102 min": .structured(StructuredDose(value: "102", unit: DoseUnit(rawValue: "minutes")!)),
        "105 min": .structured(StructuredDose(value: "105", unit: DoseUnit(rawValue: "minutes")!)),
        "117 min": .structured(StructuredDose(value: "117", unit: DoseUnit(rawValue: "minutes")!)),
        "130 min": .structured(StructuredDose(value: "130", unit: DoseUnit(rawValue: "minutes")!)),
        "10 sec": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "seconds")!)),
        "12 sec": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "seconds")!)),
        "15 sec": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "seconds")!)),
        "55 sec": .structured(StructuredDose(value: "55", unit: DoseUnit(rawValue: "seconds")!)),
        "35 sec par côté": .structured(StructuredDose(value: "35", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "1 km": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "kilometers")!)),
        "2 km": .structured(StructuredDose(value: "2", unit: DoseUnit(rawValue: "kilometers")!)),
        "3 km": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "kilometers")!)),
        "4 km": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "kilometers")!)),
        "5 km": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "kilometers")!)),
        "6 km": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "kilometers")!)),
        "7 km": .structured(StructuredDose(value: "7", unit: DoseUnit(rawValue: "kilometers")!)),
        "7.5 km": .structured(StructuredDose(value: "7.5", unit: DoseUnit(rawValue: "kilometers")!)),
        "8 km": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "kilometers")!)),
        "9 km": .structured(StructuredDose(value: "9", unit: DoseUnit(rawValue: "kilometers")!)),
        "10 km": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "kilometers")!)),
        "11 km": .structured(StructuredDose(value: "11", unit: DoseUnit(rawValue: "kilometers")!)),
        "12 km": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "kilometers")!)),
        "13 km": .structured(StructuredDose(value: "13", unit: DoseUnit(rawValue: "kilometers")!)),
        "14 km": .structured(StructuredDose(value: "14", unit: DoseUnit(rawValue: "kilometers")!)),
        "15 km": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "kilometers")!)),
        "16 km": .structured(StructuredDose(value: "16", unit: DoseUnit(rawValue: "kilometers")!)),
        "18 km": .structured(StructuredDose(value: "18", unit: DoseUnit(rawValue: "kilometers")!)),
        "20 km": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "kilometers")!)),
        "21 km": .structured(StructuredDose(value: "21", unit: DoseUnit(rawValue: "kilometers")!)),
        "24 km": .structured(StructuredDose(value: "24", unit: DoseUnit(rawValue: "kilometers")!)),
        "42,2 km": .structured(StructuredDose(value: "42.2", unit: DoseUnit(rawValue: "kilometers")!)),
        "400 m": .structured(StructuredDose(value: "400", unit: DoseUnit(rawValue: "meters")!)),
        "600 m": .structured(StructuredDose(value: "600", unit: DoseUnit(rawValue: "meters")!)),
        "600m": .structured(StructuredDose(value: "600", unit: DoseUnit(rawValue: "meters")!)),
        "800 m": .structured(StructuredDose(value: "800", unit: DoseUnit(rawValue: "meters")!)),
        "800m": .structured(StructuredDose(value: "800", unit: DoseUnit(rawValue: "meters")!)),
        "1000 m": .structured(StructuredDose(value: "1000", unit: DoseUnit(rawValue: "meters")!)),
        "1000m": .structured(StructuredDose(value: "1000", unit: DoseUnit(rawValue: "meters")!)),
        "1200m": .structured(StructuredDose(value: "1200", unit: DoseUnit(rawValue: "meters")!)),
        "600m (≈ 2 min 20 - 2 min 45 selon ton niveau)": .freeText(LocalizedText(fr: "600 m (≈ 2 min 20 - 2 min 45 selon ton niveau)", en: "600 m (≈ 2 min 20 - 2 min 45 depending on your level)", es: "600 m (≈ 2 min 20 - 2 min 45 según tu nivel)")),
        "800m (≈ 3 min - 3 min 40)": .freeText(LocalizedText(fr: "800 m (≈ 3 min - 3 min 40)", en: "800 m (≈ 3 min - 3 min 40)", es: "800 m (≈ 3 min - 3 min 40)")),
        "1 mile (≈ 6 min - 7 min 30)": .freeText(LocalizedText(fr: "1 mile (≈ 6 min - 7 min 30)", en: "1 mile (≈ 6 min - 7 min 30)", es: "1 milla (≈ 6 min - 7 min 30)")),
        "1000m (≈ 3 min 50 - 4 min 30)": .freeText(LocalizedText(fr: "1000 m (≈ 3 min 50 - 4 min 30)", en: "1000 m (≈ 3 min 50 - 4 min 30)", es: "1000 m (≈ 3 min 50 - 4 min 30)")),
        "2 km (≈ 8 min - 9 min 30)": .freeText(LocalizedText(fr: "2 km (≈ 8 min - 9 min 30)", en: "2 km (≈ 8 min - 9 min 30)", es: "2 km (≈ 8 min - 9 min 30)")),
        "1200m (≈ 4 min 40 - 5 min 30)": .freeText(LocalizedText(fr: "1200 m (≈ 4 min 40 - 5 min 30)", en: "1200 m (≈ 4 min 40 - 5 min 30)", es: "1200 m (≈ 4 min 40 - 5 min 30)")),
        "105-120 min selon objectif": .freeText(LocalizedText(fr: "105-120 min selon ton objectif", en: "105-120 min depending on your goal", es: "105-120 min según tu objetivo")),
        "5 km à effort contrôlé (pas sprint maximal)": .freeText(LocalizedText(fr: "5 km à effort contrôlé (pas un sprint maximal)", en: "5 km at controlled effort (not an all-out sprint)", es: "5 km a esfuerzo controlado (no un sprint máximo)")),
        "4 min course": .interval([IntervalSegment(value: "4", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "running")!)]),
        "5 min course": .interval([IntervalSegment(value: "5", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "running")!)]),
        "8 min course": .interval([IntervalSegment(value: "8", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "running")!)]),
        "20 sec accélération progressive": .interval([IntervalSegment(value: "20", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "accelerationProgressive")!)]),
        "3 min course + 2 min marche": .interval([IntervalSegment(value: "3", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "running")!), IntervalSegment(value: "2", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "walking")!)]),
        "5 min course + 2 min marche": .interval([IntervalSegment(value: "5", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "running")!), IntervalSegment(value: "2", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "walking")!)]),
        "1 min 30 course + 2 min marche": .freeText(LocalizedText(fr: "1 min 30 de course + 2 min de marche", en: "1 min 30 running + 2 min walking", es: "1 min 30 de carrera + 2 min de caminata")),
        "1 min course lente + 1 min 30 marche rapide": .freeText(LocalizedText(fr: "1 min de course lente + 1 min 30 de marche rapide", en: "1 min slow running + 1 min 30 brisk walking", es: "1 min de carrera lenta + 1 min 30 de caminata rápida")),
        "1 min 30 course + 1 min 30 marche + 3 min course + 3 min marche": .freeText(LocalizedText(fr: "1 min 30 de course + 1 min 30 de marche + 3 min de course + 3 min de marche", en: "1 min 30 running + 1 min 30 walking + 3 min running + 3 min walking", es: "1 min 30 de carrera + 1 min 30 de caminata + 3 min de carrera + 3 min de caminata")),
        "100 m accélération progressive + 60 sec marche récupération": .interval([IntervalSegment(value: "100", unit: DoseUnit(rawValue: "meters")!, activity: DoseActivity(rawValue: "accelerationProgressive")!), IntervalSegment(value: "60", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "walkingRecovery")!)]),
        "60 m à allure cible 10K + 60 sec marche récupération": .interval([IntervalSegment(value: "60", unit: DoseUnit(rawValue: "meters")!, activity: DoseActivity(rawValue: "pace10K")!), IntervalSegment(value: "60", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "walkingRecovery")!)]),
        "1 min à allure 5K (RPE 8) + 1 min footing easy (facile (tu peux parler))": .interval([IntervalSegment(value: "1", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "pace5K")!), IntervalSegment(value: "1", unit: DoseUnit(rawValue: "minutes")!, activity: DoseActivity(rawValue: "easyJog")!)]),
        "1 min à allure 5K (RPE 8) + 1 min 30 footing easy (facile (tu peux parler))": .freeText(LocalizedText(fr: "1 min à allure 5K + 1 min 30 de footing tranquille", en: "1 min at 5K pace + 1 min 30 easy jogging", es: "1 min a ritmo 5K + 1 min 30 de trote suave")),
        "1 min 30 à allure 5K (RPE 8) + 1 min 30 footing easy (facile (tu peux parler))": .freeText(LocalizedText(fr: "1 min 30 à allure 5K + 1 min 30 de footing tranquille", en: "1 min 30 at 5K pace + 1 min 30 easy jogging", es: "1 min 30 a ritmo 5K + 1 min 30 de trote suave")),
        "5": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "reps")!)),
        "6": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "reps")!)),
        "7": .structured(StructuredDose(value: "7", unit: DoseUnit(rawValue: "reps")!)),
        "8": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!)),
        "10": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!)),
        "12": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!)),
        "15": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "reps")!)),
        "20": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "reps")!)),
        "5-6": .structured(StructuredDose(value: "5-6", unit: DoseUnit(rawValue: "reps")!)),
        "6-7": .structured(StructuredDose(value: "6-7", unit: DoseUnit(rawValue: "reps")!)),
        "7-8": .structured(StructuredDose(value: "7-8", unit: DoseUnit(rawValue: "reps")!)),
        "8 par côté": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "10 par côté": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "12 par côté": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "15 par côté": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "6 par jambe": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "8 par jambe": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "10 par jambe": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "12 par jambe": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "15 par jambe": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "16 par jambe": .structured(StructuredDose(value: "16", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "18 par jambe": .structured(StructuredDose(value: "18", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        // ====================== LOT 3 — CYCLING (généré, ne pas éditer) ======================
        "33 min": .structured(StructuredDose(value: "33", unit: DoseUnit(rawValue: "minutes")!)),
        "45 min": .structured(StructuredDose(value: "45", unit: DoseUnit(rawValue: "minutes")!)),
        "47 min": .structured(StructuredDose(value: "47", unit: DoseUnit(rawValue: "minutes")!)),
        "64 min": .structured(StructuredDose(value: "64", unit: DoseUnit(rawValue: "minutes")!)),
        "68 min": .structured(StructuredDose(value: "68", unit: DoseUnit(rawValue: "minutes")!)),
        "72 min": .structured(StructuredDose(value: "72", unit: DoseUnit(rawValue: "minutes")!)),
        "77 min": .structured(StructuredDose(value: "77", unit: DoseUnit(rawValue: "minutes")!)),
        "80 min": .structured(StructuredDose(value: "80", unit: DoseUnit(rawValue: "minutes")!)),
        "85 min": .structured(StructuredDose(value: "85", unit: DoseUnit(rawValue: "minutes")!)),
        "90 min": .structured(StructuredDose(value: "90", unit: DoseUnit(rawValue: "minutes")!)),
        "95 min": .structured(StructuredDose(value: "95", unit: DoseUnit(rawValue: "minutes")!)),
        "100 min": .structured(StructuredDose(value: "100", unit: DoseUnit(rawValue: "minutes")!)),
        "110 min": .structured(StructuredDose(value: "110", unit: DoseUnit(rawValue: "minutes")!)),
        "120 min": .structured(StructuredDose(value: "120", unit: DoseUnit(rawValue: "minutes")!)),
        "125 min": .structured(StructuredDose(value: "125", unit: DoseUnit(rawValue: "minutes")!)),
        "135 min": .structured(StructuredDose(value: "135", unit: DoseUnit(rawValue: "minutes")!)),
        "140 min": .structured(StructuredDose(value: "140", unit: DoseUnit(rawValue: "minutes")!)),
        "145 min": .structured(StructuredDose(value: "145", unit: DoseUnit(rawValue: "minutes")!)),
        "150 min": .structured(StructuredDose(value: "150", unit: DoseUnit(rawValue: "minutes")!)),
        "153 min": .structured(StructuredDose(value: "153", unit: DoseUnit(rawValue: "minutes")!)),
        "155 min": .structured(StructuredDose(value: "155", unit: DoseUnit(rawValue: "minutes")!)),
        "160 min": .structured(StructuredDose(value: "160", unit: DoseUnit(rawValue: "minutes")!)),
        "170 min": .structured(StructuredDose(value: "170", unit: DoseUnit(rawValue: "minutes")!)),
        "180 min": .structured(StructuredDose(value: "180", unit: DoseUnit(rawValue: "minutes")!)),
        "190 min": .structured(StructuredDose(value: "190", unit: DoseUnit(rawValue: "minutes")!)),
        "195 min": .structured(StructuredDose(value: "195", unit: DoseUnit(rawValue: "minutes")!)),
        "200 min": .structured(StructuredDose(value: "200", unit: DoseUnit(rawValue: "minutes")!)),
        "210 min": .structured(StructuredDose(value: "210", unit: DoseUnit(rawValue: "minutes")!)),
        "220 min": .structured(StructuredDose(value: "220", unit: DoseUnit(rawValue: "minutes")!)),
        "225 min": .structured(StructuredDose(value: "225", unit: DoseUnit(rawValue: "minutes")!)),
        "230 min": .structured(StructuredDose(value: "230", unit: DoseUnit(rawValue: "minutes")!)),
        "235 min": .structured(StructuredDose(value: "235", unit: DoseUnit(rawValue: "minutes")!)),
        "250 min": .structured(StructuredDose(value: "250", unit: DoseUnit(rawValue: "minutes")!)),
        "255 min": .structured(StructuredDose(value: "255", unit: DoseUnit(rawValue: "minutes")!)),
        "265 min": .structured(StructuredDose(value: "265", unit: DoseUnit(rawValue: "minutes")!)),
        "270 min": .structured(StructuredDose(value: "270", unit: DoseUnit(rawValue: "minutes")!)),
        "290 min": .structured(StructuredDose(value: "290", unit: DoseUnit(rawValue: "minutes")!)),
        "300 min": .structured(StructuredDose(value: "300", unit: DoseUnit(rawValue: "minutes")!)),
        "300-330 min": .structured(StructuredDose(value: "300-330", unit: DoseUnit(rawValue: "minutes")!)),
        "~150 min": .structured(StructuredDose(value: "~150", unit: DoseUnit(rawValue: "minutes")!)),
        "~65 min": .structured(StructuredDose(value: "~65", unit: DoseUnit(rawValue: "minutes")!)),
        "5 min tempo soutenu": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "minutes")!)),
        "8 min tempo soutenu": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "minutes")!)),
        "10 min tempo soutenu": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "minutes")!)),
        "12 min tempo soutenu": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "minutes")!)),
        "15 min tempo soutenu": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "minutes")!)),
        "20 min tempo soutenu": .structured(StructuredDose(value: "20", unit: DoseUnit(rawValue: "minutes")!)),
        "25 sec par côté": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "60 sec par jambe": .structured(StructuredDose(value: "60", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "40 sec par position": .structured(StructuredDose(value: "40", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perPosition")!)),
        "6-8": .structured(StructuredDose(value: "6-8", unit: DoseUnit(rawValue: "reps")!)),
        "25 km / ~55 min": .freeText(LocalizedText(fr: "25 km / ~55 min", en: "25 km / ~55 min", es: "25 km / ~55 min")),
        "25 km / ~60 min": .freeText(LocalizedText(fr: "25 km / ~60 min", en: "25 km / ~60 min", es: "25 km / ~60 min")),
        "28 km / ~55 min": .freeText(LocalizedText(fr: "28 km / ~55 min", en: "28 km / ~55 min", es: "28 km / ~55 min")),
        "28 km / ~65 min": .freeText(LocalizedText(fr: "28 km / ~65 min", en: "28 km / ~65 min", es: "28 km / ~65 min")),
        "30 km / ~70 min": .freeText(LocalizedText(fr: "30 km / ~70 min", en: "30 km / ~70 min", es: "30 km / ~70 min")),
        "32 km / ~75 min": .freeText(LocalizedText(fr: "32 km / ~75 min", en: "32 km / ~75 min", es: "32 km / ~75 min")),
        "35 km / ~70 min": .freeText(LocalizedText(fr: "35 km / ~70 min", en: "35 km / ~70 min", es: "35 km / ~70 min")),
        "35 km / ~80 min": .freeText(LocalizedText(fr: "35 km / ~80 min", en: "35 km / ~80 min", es: "35 km / ~80 min")),
        "40 km / ~85 min": .freeText(LocalizedText(fr: "40 km / ~85 min", en: "40 km / ~85 min", es: "40 km / ~85 min")),
        "45 km / ~95 min": .freeText(LocalizedText(fr: "45 km / ~95 min", en: "45 km / ~95 min", es: "45 km / ~95 min")),
        "50 km / ~105 min": .freeText(LocalizedText(fr: "50 km / ~105 min", en: "50 km / ~105 min", es: "50 km / ~105 min")),
        "52 km / ~108 min": .freeText(LocalizedText(fr: "52 km / ~108 min", en: "52 km / ~108 min", es: "52 km / ~108 min")),
        "60 km / ~125 min": .freeText(LocalizedText(fr: "60 km / ~125 min", en: "60 km / ~125 min", es: "60 km / ~125 min")),
        "62 km / ~110 min": .freeText(LocalizedText(fr: "62 km / ~110 min", en: "62 km / ~110 min", es: "62 km / ~110 min")),
        "62 km / ~130 min": .freeText(LocalizedText(fr: "62 km / ~130 min", en: "62 km / ~130 min", es: "62 km / ~130 min")),
        "65 km / ~115 min": .freeText(LocalizedText(fr: "65 km / ~115 min", en: "65 km / ~115 min", es: "65 km / ~115 min")),
        "65 km / ~135 min": .freeText(LocalizedText(fr: "65 km / ~135 min", en: "65 km / ~135 min", es: "65 km / ~135 min")),
        "72 km / ~150 min": .freeText(LocalizedText(fr: "72 km / ~150 min", en: "72 km / ~150 min", es: "72 km / ~150 min")),
        "78 km / ~165 min": .freeText(LocalizedText(fr: "78 km / ~165 min", en: "78 km / ~165 min", es: "78 km / ~165 min")),
        "80 km / ~180 min": .freeText(LocalizedText(fr: "80 km / ~180 min", en: "80 km / ~180 min", es: "80 km / ~180 min")),
        "82 km / ~175 min": .freeText(LocalizedText(fr: "82 km / ~175 min", en: "82 km / ~175 min", es: "82 km / ~175 min")),
        "180-220 km / 3000+ m D+": .freeText(LocalizedText(fr: "180-220 km / 3000+ m D+", en: "180-220 km / 3000+ m elevation gain", es: "180-220 km / 3000+ m de desnivel")),
        "2 min en montée": .freeText(LocalizedText(fr: "2 min en montée", en: "2 min uphill", es: "2 min en subida")),
        "2 min à 100-105 rpm": .freeText(LocalizedText(fr: "2 min à 100-105 rpm", en: "2 min at 100-105 rpm", es: "2 min a 100-105 rpm")),
        "3 min à 100-105 rpm en endurance facile": .freeText(LocalizedText(fr: "3 min à 100-105 rpm en endurance facile", en: "3 min at 100-105 rpm, easy endurance", es: "3 min a 100-105 rpm, resistencia fácil")),
        "3 min à 95-100 rpm + 3 min à 85 rpm": .freeText(LocalizedText(fr: "3 min à 95-100 rpm + 3 min à 85 rpm", en: "3 min at 95-100 rpm + 3 min at 85 rpm", es: "3 min a 95-100 rpm + 3 min a 85 rpm")),
        "8 min tempo + 5 min endurance facile récupération": .freeText(LocalizedText(fr: "8 min tempo + 5 min d'endurance facile en récupération", en: "8 min tempo + 5 min easy recovery", es: "8 min tempo + 5 min de recuperación fácil")),
        "8 par côté + 30 sec planche dorsale": .freeText(LocalizedText(fr: "8 par côté + 30 s de planche dorsale", en: "8 per side + 30 s reverse plank", es: "8 por lado + 30 s de plancha invertida")),
        "Journée entière": .freeText(LocalizedText(fr: "Journée entière", en: "Full day", es: "Jornada completa")),
        // ====================== LOT 4 — SWIMMING (généré, ne pas éditer) ======================
        "25 m": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "meters")!)),
        "50 m": .structured(StructuredDose(value: "50", unit: DoseUnit(rawValue: "meters")!)),
        "75 m": .structured(StructuredDose(value: "75", unit: DoseUnit(rawValue: "meters")!)),
        "100 m": .structured(StructuredDose(value: "100", unit: DoseUnit(rawValue: "meters")!)),
        "150 m": .structured(StructuredDose(value: "150", unit: DoseUnit(rawValue: "meters")!)),
        "175 m": .structured(StructuredDose(value: "175", unit: DoseUnit(rawValue: "meters")!)),
        "200 m": .structured(StructuredDose(value: "200", unit: DoseUnit(rawValue: "meters")!)),
        "250 m": .structured(StructuredDose(value: "250", unit: DoseUnit(rawValue: "meters")!)),
        "300 m": .structured(StructuredDose(value: "300", unit: DoseUnit(rawValue: "meters")!)),
        "500 m": .structured(StructuredDose(value: "500", unit: DoseUnit(rawValue: "meters")!)),
        "1200 m": .structured(StructuredDose(value: "1200", unit: DoseUnit(rawValue: "meters")!)),
        "1300 m": .structured(StructuredDose(value: "1300", unit: DoseUnit(rawValue: "meters")!)),
        "1500 m": .structured(StructuredDose(value: "1500", unit: DoseUnit(rawValue: "meters")!)),
        "1800 m": .structured(StructuredDose(value: "1800", unit: DoseUnit(rawValue: "meters")!)),
        "2000 m": .structured(StructuredDose(value: "2000", unit: DoseUnit(rawValue: "meters")!)),
        "2200 m": .structured(StructuredDose(value: "2200", unit: DoseUnit(rawValue: "meters")!)),
        "2300 m": .structured(StructuredDose(value: "2300", unit: DoseUnit(rawValue: "meters")!)),
        "2400 m": .structured(StructuredDose(value: "2400", unit: DoseUnit(rawValue: "meters")!)),
        "2500 m": .structured(StructuredDose(value: "2500", unit: DoseUnit(rawValue: "meters")!)),
        "2600 m": .structured(StructuredDose(value: "2600", unit: DoseUnit(rawValue: "meters")!)),
        "2700 m": .structured(StructuredDose(value: "2700", unit: DoseUnit(rawValue: "meters")!)),
        "3000 m": .structured(StructuredDose(value: "3000", unit: DoseUnit(rawValue: "meters")!)),
        "3200 m": .structured(StructuredDose(value: "3200", unit: DoseUnit(rawValue: "meters")!)),
        "3300 m": .structured(StructuredDose(value: "3300", unit: DoseUnit(rawValue: "meters")!)),
        "100 m endurance haute": .structured(StructuredDose(value: "100", unit: DoseUnit(rawValue: "meters")!)),
        "150 m endurance haute": .structured(StructuredDose(value: "150", unit: DoseUnit(rawValue: "meters")!)),
        "200 m endurance haute": .structured(StructuredDose(value: "200", unit: DoseUnit(rawValue: "meters")!)),
        "50 m rapide": .structured(StructuredDose(value: "50", unit: DoseUnit(rawValue: "meters")!)),
        "25 m très rapide": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "meters")!)),
        "25 m sprint vitesse max": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "meters")!)),
        "25 m vitesse libre 80-90%": .structured(StructuredDose(value: "25", unit: DoseUnit(rawValue: "meters")!)),
        "400 m à allure régulière": .structured(StructuredDose(value: "400", unit: DoseUnit(rawValue: "meters")!)),
        "1000 m à allure régulière": .structured(StructuredDose(value: "1000", unit: DoseUnit(rawValue: "meters")!)),
        "500 m à allure seuil pace": .structured(StructuredDose(value: "500", unit: DoseUnit(rawValue: "meters")!)),
        "400 m continu": .structured(StructuredDose(value: "400", unit: DoseUnit(rawValue: "meters")!)),
        "500 m continu": .structured(StructuredDose(value: "500", unit: DoseUnit(rawValue: "meters")!)),
        "600 m continu": .structured(StructuredDose(value: "600", unit: DoseUnit(rawValue: "meters")!)),
        "700 m continu": .structured(StructuredDose(value: "700", unit: DoseUnit(rawValue: "meters")!)),
        "800 m continu": .structured(StructuredDose(value: "800", unit: DoseUnit(rawValue: "meters")!)),
        "1000 m continu": .structured(StructuredDose(value: "1000", unit: DoseUnit(rawValue: "meters")!)),
        "1300 m continu": .structured(StructuredDose(value: "1300", unit: DoseUnit(rawValue: "meters")!)),
        "10 reps": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!)),
        "12 reps": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!)),
        "14": .structured(StructuredDose(value: "14", unit: DoseUnit(rawValue: "reps")!)),
        "12 par bras": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perArm")!)),
        "14 par côté": .structured(StructuredDose(value: "14", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "12 reps par côté": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "15 reps par côté": .structured(StructuredDose(value: "15", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "10 par lettre": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "12 par lettre": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "10 reps par lettre": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "12 reps par lettre": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "8 par lettre (Y, T, W)": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "25 m crawl lent": .freeText(LocalizedText(fr: "25 m crawl lent", en: "25 m easy freestyle", es: "25 m crol suave")),
        "200 m crawl lent": .freeText(LocalizedText(fr: "200 m crawl lent", en: "200 m easy freestyle", es: "200 m crol suave")),
        "200 m crawl endurance facile": .freeText(LocalizedText(fr: "200 m crawl, endurance facile", en: "200 m freestyle, easy endurance", es: "200 m crol, resistencia fácil")),
        "100 m dos crawl très lent": .freeText(LocalizedText(fr: "100 m dos très lent", en: "100 m very easy backstroke", es: "100 m espalda muy suave")),
        "150 m dos lent": .freeText(LocalizedText(fr: "150 m dos lent", en: "150 m easy backstroke", es: "150 m espalda suave")),
        "200 m dos lent": .freeText(LocalizedText(fr: "200 m dos lent", en: "200 m easy backstroke", es: "200 m espalda suave")),
        "100 m crawl lent compteur cycles": .freeText(LocalizedText(fr: "100 m crawl lent, comptage des cycles", en: "100 m easy freestyle, stroke count", es: "100 m crol suave, conteo de brazadas")),
        "150 m crawl lent compteur cycles": .freeText(LocalizedText(fr: "150 m crawl lent, comptage des cycles", en: "150 m easy freestyle, stroke count", es: "150 m crol suave, conteo de brazadas")),
        "100 m crawl + 20 s récup": .freeText(LocalizedText(fr: "100 m crawl + 20 s de récup", en: "100 m freestyle + 20 s rest", es: "100 m crol + 20 s de descanso")),
        "100 m crawl bilatérale 1/3 + 25 s récup": .freeText(LocalizedText(fr: "100 m crawl, respiration bilatérale 1/3 + 25 s de récup", en: "100 m freestyle, bilateral breathing 1/3 + 25 s rest", es: "100 m crol, respiración bilateral 1/3 + 25 s de descanso")),
        "100 m crawl endurance haute + 45 s récup": .freeText(LocalizedText(fr: "100 m crawl, endurance haute + 45 s de récup", en: "100 m freestyle, high endurance + 45 s rest", es: "100 m crol, resistencia alta + 45 s de descanso")),
        "100 m crawl endurance soutenue + 20 s récup": .freeText(LocalizedText(fr: "100 m crawl, endurance soutenue + 20 s de récup", en: "100 m freestyle, sustained endurance + 20 s rest", es: "100 m crol, resistencia sostenida + 20 s de descanso")),
        "100 m crawl endurance soutenue + 25 s récup": .freeText(LocalizedText(fr: "100 m crawl, endurance soutenue + 25 s de récup", en: "100 m freestyle, sustained endurance + 25 s rest", es: "100 m crol, resistencia sostenida + 25 s de descanso")),
        "200 m crawl endurance facile récup 60 s": .freeText(LocalizedText(fr: "200 m crawl, endurance facile, récup 60 s", en: "200 m freestyle, easy endurance, 60 s rest", es: "200 m crol, resistencia fácil, 60 s de descanso")),
        "50 m crawl avec pull-buoy entre les jambes + 20 s récup": .freeText(LocalizedText(fr: "50 m crawl avec pull-buoy + 20 s de récup", en: "50 m freestyle with pull-buoy + 20 s rest", es: "50 m crol con pull-buoy + 20 s de descanso")),
        "100 m à allure seuil+3s/100m": .freeText(LocalizedText(fr: "100 m à allure seuil + 3 s/100 m", en: "100 m at threshold pace + 3 s/100 m", es: "100 m a ritmo umbral + 3 s/100 m")),
        "100 m à allure seuil+5s/100m": .freeText(LocalizedText(fr: "100 m à allure seuil + 5 s/100 m", en: "100 m at threshold pace + 5 s/100 m", es: "100 m a ritmo umbral + 5 s/100 m")),
        "200 m à allure seuil+2s/100m": .freeText(LocalizedText(fr: "200 m à allure seuil + 2 s/100 m", en: "200 m at threshold pace + 2 s/100 m", es: "200 m a ritmo umbral + 2 s/100 m")),
        "1 poussée + glisse 5 m": .freeText(LocalizedText(fr: "1 poussée au mur + glisse 5 m", en: "1 wall push-off + 5 m glide", es: "1 impulso en la pared + 5 m de deslizamiento")),
        "1 poussée + glisse 8 m": .freeText(LocalizedText(fr: "1 poussée au mur + glisse 8 m", en: "1 wall push-off + 8 m glide", es: "1 impulso en la pared + 8 m de deslizamiento")),
        "1 poussée + glisse max": .freeText(LocalizedText(fr: "1 poussée au mur + glisse maximale", en: "1 wall push-off + max glide", es: "1 impulso en la pared + deslizamiento máximo")),
        "10 m glissé apnée": .freeText(LocalizedText(fr: "10 m en glisse, apnée", en: "10 m glide, breath-hold", es: "10 m de deslizamiento, en apnea")),
        "10 sec expiration": .freeText(LocalizedText(fr: "10 s d'expiration", en: "10 s exhale", es: "10 s de exhalación")),
        "10 sec flottaison + 5 m glisse": .freeText(LocalizedText(fr: "10 s de flottaison + 5 m de glisse", en: "10 s float + 5 m glide", es: "10 s de flotación + 5 m de deslizamiento")),
        "15 m avancée": .freeText(LocalizedText(fr: "15 m de godille vers l'avant", en: "15 m sculling forward", es: "15 m de godella hacia adelante")),
        "10 cycles lents": .freeText(LocalizedText(fr: "10 cycles lents", en: "10 slow cycles", es: "10 ciclos lentos")),
        "25 m côté favori": .freeText(LocalizedText(fr: "25 m côté favori", en: "25 m favourite side", es: "25 m lado favorito")),
        "25 m (alterner côté favori et côté faible)": .freeText(LocalizedText(fr: "25 m (alterner côté favori et côté faible)", en: "25 m (alternate favourite and weak side)", es: "25 m (alternar lado favorito y lado débil)")),
        "25 m (alterner côtés)": .freeText(LocalizedText(fr: "25 m (alterner les côtés)", en: "25 m (alternate sides)", es: "25 m (alternar lados)")),
        "25 m bras tendus devant figures-8 lentes (pull-buoy entre les jambes)": .freeText(LocalizedText(fr: "25 m bras tendus devant, figures en 8 lentes (pull-buoy)", en: "25 m arms extended forward, slow figure-8s (pull-buoy)", es: "25 m brazos extendidos al frente, ochos lentos (pull-buoy)")),
        "25 m drill + 25 m crawl endurance facile (50 m total par série)": .freeText(LocalizedText(fr: "25 m éducatif + 25 m crawl facile (50 m par série)", en: "25 m drill + 25 m easy freestyle (50 m per set)", es: "25 m de técnica + 25 m crol suave (50 m por serie)")),
        "50 m rapide, récup 90 s entre 50 m, récup 4 min entre séries de 4": .freeText(LocalizedText(fr: "50 m rapide, récup 90 s entre les 50 m, récup 4 min entre les séries de 4", en: "50 m fast, 90 s rest between 50 m, 4 min rest between sets of 4", es: "50 m rápido, 90 s de descanso entre los 50 m, 4 min entre series de 4")),
        "3500 m continu OU 30 × 100 m à allure seuil récup 10 s (3000 m qualité)": .freeText(LocalizedText(fr: "3500 m en continu OU 30 × 100 m à allure seuil, récup 10 s (3000 m qualité)", en: "3500 m continuous OR 30 × 100 m at threshold pace, 10 s rest (3000 m quality)", es: "3500 m continuo O 30 × 100 m a ritmo umbral, 10 s de descanso (3000 m de calidad)")),
        "Auto-évaluation post-séance": .freeText(LocalizedText(fr: "Auto-évaluation post-séance", en: "Post-session self-assessment", es: "Autoevaluación post-sesión")),
        // ====================== LOT 5 — HIKING (généré, ne pas éditer) ======================
        "4 h": .freeText(LocalizedText(fr: "4 h", en: "4 h", es: "4 h")),
        "4 h 30": .freeText(LocalizedText(fr: "4 h 30", en: "4 h 30", es: "4 h 30")),
        "6 h": .freeText(LocalizedText(fr: "6 h", en: "6 h", es: "6 h")),
        "6 h 30": .freeText(LocalizedText(fr: "6 h 30", en: "6 h 30", es: "6 h 30")),
        "7 h": .freeText(LocalizedText(fr: "7 h", en: "7 h", es: "7 h")),
        "7 h 30": .freeText(LocalizedText(fr: "7 h 30", en: "7 h 30", es: "7 h 30")),
        "8 h": .freeText(LocalizedText(fr: "8 h", en: "8 h", es: "8 h")),
        "8 h 30": .freeText(LocalizedText(fr: "8 h 30", en: "8 h 30", es: "8 h 30")),
        "9 h": .freeText(LocalizedText(fr: "9 h", en: "9 h", es: "9 h")),
        "9 h 30": .freeText(LocalizedText(fr: "9 h 30", en: "9 h 30", es: "9 h 30")),
        "10 h": .freeText(LocalizedText(fr: "10 h", en: "10 h", es: "10 h")),
        "11 h": .freeText(LocalizedText(fr: "11 h", en: "11 h", es: "11 h")),
        "240 min": .structured(StructuredDose(value: "240", unit: DoseUnit(rawValue: "minutes")!)),
        "275 min": .structured(StructuredDose(value: "275", unit: DoseUnit(rawValue: "minutes")!)),
        "330 min": .structured(StructuredDose(value: "330", unit: DoseUnit(rawValue: "minutes")!)),
        "360 min": .structured(StructuredDose(value: "360", unit: DoseUnit(rawValue: "minutes")!)),
        "390 min": .structured(StructuredDose(value: "390", unit: DoseUnit(rawValue: "minutes")!)),
        "60 min marche / D+ 100 m / sac 8 kg": .freeText(LocalizedText(fr: "60 min de marche / D+ 100 m / sac 8 kg", en: "60 min walk / 100 m elevation gain / 8 kg pack", es: "60 min de caminata / 100 m de desnivel / mochila 8 kg")),
        "70 min marche / D+ 180 m / sac 5 kg": .freeText(LocalizedText(fr: "70 min de marche / D+ 180 m / sac 5 kg", en: "70 min walk / 180 m elevation gain / 5 kg pack", es: "70 min de caminata / 180 m de desnivel / mochila 5 kg")),
        "75 min marche / D+ 150 m / sac 4 kg": .freeText(LocalizedText(fr: "75 min de marche / D+ 150 m / sac 4 kg", en: "75 min walk / 150 m elevation gain / 4 kg pack", es: "75 min de caminata / 150 m de desnivel / mochila 4 kg")),
        "85 min marche / D+ 200 m / sac 5 kg": .freeText(LocalizedText(fr: "85 min de marche / D+ 200 m / sac 5 kg", en: "85 min walk / 200 m elevation gain / 5 kg pack", es: "85 min de caminata / 200 m de desnivel / mochila 5 kg")),
        "90 min marche / D+ 250 m / sac 6 kg": .freeText(LocalizedText(fr: "90 min de marche / D+ 250 m / sac 6 kg", en: "90 min walk / 250 m elevation gain / 6 kg pack", es: "90 min de caminata / 250 m de desnivel / mochila 6 kg")),
        "100 min marche / D+ 280 m / sac 6 kg": .freeText(LocalizedText(fr: "100 min de marche / D+ 280 m / sac 6 kg", en: "100 min walk / 280 m elevation gain / 6 kg pack", es: "100 min de caminata / 280 m de desnivel / mochila 6 kg")),
        "100 min marche / D+ 300 m / sac 5 kg": .freeText(LocalizedText(fr: "100 min de marche / D+ 300 m / sac 5 kg", en: "100 min walk / 300 m elevation gain / 5 kg pack", es: "100 min de caminata / 300 m de desnivel / mochila 5 kg")),
        "105 min marche / D+ 250 m / sac 4 kg": .freeText(LocalizedText(fr: "105 min de marche / D+ 250 m / sac 4 kg", en: "105 min walk / 250 m elevation gain / 4 kg pack", es: "105 min de caminata / 250 m de desnivel / mochila 4 kg")),
        "110 min marche / D+ 320 m / sac 7 kg": .freeText(LocalizedText(fr: "110 min de marche / D+ 320 m / sac 7 kg", en: "110 min walk / 320 m elevation gain / 7 kg pack", es: "110 min de caminata / 320 m de desnivel / mochila 7 kg")),
        "120 min marche / D+ 350 m / sac 7 kg": .freeText(LocalizedText(fr: "120 min de marche / D+ 350 m / sac 7 kg", en: "120 min walk / 350 m elevation gain / 7 kg pack", es: "120 min de caminata / 350 m de desnivel / mochila 7 kg")),
        "130 min marche / D+ 350 m / sac 5 kg": .freeText(LocalizedText(fr: "130 min de marche / D+ 350 m / sac 5 kg", en: "130 min walk / 350 m elevation gain / 5 kg pack", es: "130 min de caminata / 350 m de desnivel / mochila 5 kg")),
        "130 min marche / D+ 380 m / sac 8 kg": .freeText(LocalizedText(fr: "130 min de marche / D+ 380 m / sac 8 kg", en: "130 min walk / 380 m elevation gain / 8 kg pack", es: "130 min de caminata / 380 m de desnivel / mochila 8 kg")),
        "150 min marche / D+ 450 m / sac 6 kg": .freeText(LocalizedText(fr: "150 min de marche / D+ 450 m / sac 6 kg", en: "150 min walk / 450 m elevation gain / 6 kg pack", es: "150 min de caminata / 450 m de desnivel / mochila 6 kg")),
        "160 min marche / D+ 530 m / sac 6 kg": .freeText(LocalizedText(fr: "160 min de marche / D+ 530 m / sac 6 kg", en: "160 min walk / 530 m elevation gain / 6 kg pack", es: "160 min de caminata / 530 m de desnivel / mochila 6 kg")),
        "180 min marche / D+ 570 m / sac 6 kg": .freeText(LocalizedText(fr: "180 min de marche / D+ 570 m / sac 6 kg", en: "180 min walk / 570 m elevation gain / 6 kg pack", es: "180 min de caminata / 570 m de desnivel / mochila 6 kg")),
        "200 min marche / D+ 680 m / sac 7 kg": .freeText(LocalizedText(fr: "200 min de marche / D+ 680 m / sac 7 kg", en: "200 min walk / 680 m elevation gain / 7 kg pack", es: "200 min de caminata / 680 m de desnivel / mochila 7 kg")),
        "220 min marche / D+ 850 m / sac 7 kg": .freeText(LocalizedText(fr: "220 min de marche / D+ 850 m / sac 7 kg", en: "220 min walk / 850 m elevation gain / 7 kg pack", es: "220 min de caminata / 850 m de desnivel / mochila 7 kg")),
        "240 min marche / D+ 950 m / sac 8 kg": .freeText(LocalizedText(fr: "240 min de marche / D+ 950 m / sac 8 kg", en: "240 min walk / 950 m elevation gain / 8 kg pack", es: "240 min de caminata / 950 m de desnivel / mochila 8 kg")),
        "5 h marche / D+ 1000 m / sac 8 kg": .freeText(LocalizedText(fr: "5 h de marche / D+ 1000 m / sac 8 kg", en: "5 h walk / 1000 m elevation gain / 8 kg pack", es: "5 h de caminata / 1000 m de desnivel / mochila 8 kg")),
        "45 min total dont 200 m D+ cumulé": .freeText(LocalizedText(fr: "45 min au total dont 200 m D+ cumulé", en: "45 min total incl. 200 m cumulative elevation gain", es: "45 min en total con 200 m de desnivel acumulado")),
        "50 min total dont 250 m D+ cumulé": .freeText(LocalizedText(fr: "50 min au total dont 250 m D+ cumulé", en: "50 min total incl. 250 m cumulative elevation gain", es: "50 min en total con 250 m de desnivel acumulado")),
        "60 min total dont 280 m D+ cumulé": .freeText(LocalizedText(fr: "60 min au total dont 280 m D+ cumulé", en: "60 min total incl. 280 m cumulative elevation gain", es: "60 min en total con 280 m de desnivel acumulado")),
        "70 min total dont 350 m D+ cumulé": .freeText(LocalizedText(fr: "70 min au total dont 350 m D+ cumulé", en: "70 min total incl. 350 m cumulative elevation gain", es: "70 min en total con 350 m de desnivel acumulado")),
        "75 min total dont 400 m D+ cumulé": .freeText(LocalizedText(fr: "75 min au total dont 400 m D+ cumulé", en: "75 min total incl. 400 m cumulative elevation gain", es: "75 min en total con 400 m de desnivel acumulado")),
        "105 min total dont 550 m D+ cumulé": .freeText(LocalizedText(fr: "105 min au total dont 550 m D+ cumulé", en: "105 min total incl. 550 m cumulative elevation gain", es: "105 min en total con 550 m de desnivel acumulado")),
        "120 min total dont 500 m D+ cumulé": .freeText(LocalizedText(fr: "120 min au total dont 500 m D+ cumulé", en: "120 min total incl. 500 m cumulative elevation gain", es: "120 min en total con 500 m de desnivel acumulado")),
        "90 min total dont 500 m D+ cumulé": .freeText(LocalizedText(fr: "90 min au total dont 500 m D+ cumulé", en: "90 min total incl. 500 m cumulative elevation gain", es: "90 min en total con 500 m de desnivel acumulado")),
        "30 min montée continue tempo sac 7 kg": .freeText(LocalizedText(fr: "30 min de montée continue tempo, sac 7 kg", en: "30 min steady tempo climb, 7 kg pack", es: "30 min de subida continua tempo, mochila 7 kg")),
        "40 min montée continue tempo sac 7 kg": .freeText(LocalizedText(fr: "40 min de montée continue tempo, sac 7 kg", en: "40 min steady tempo climb, 7 kg pack", es: "40 min de subida continua tempo, mochila 7 kg")),
        "45 min montée continue tempo sac 8 kg": .freeText(LocalizedText(fr: "45 min de montée continue tempo, sac 8 kg", en: "45 min steady tempo climb, 8 kg pack", es: "45 min de subida continua tempo, mochila 8 kg")),
        "25 min montée tempo gradient 8-10% sac 12 kg": .freeText(LocalizedText(fr: "25 min de montée tempo, pente 8-10 %, sac 12 kg", en: "25 min tempo climb, 8-10% grade, 12 kg pack", es: "25 min de subida tempo, pendiente 8-10 %, mochila 12 kg")),
        "40 min montée tempo gradient 10% sac 15 kg": .freeText(LocalizedText(fr: "40 min de montée tempo, pente 10 %, sac 15 kg", en: "40 min tempo climb, 10% grade, 15 kg pack", es: "40 min de subida tempo, pendiente 10 %, mochila 15 kg")),
        "50 min montée tempo gradient 10% sac 14 kg": .freeText(LocalizedText(fr: "50 min de montée tempo, pente 10 %, sac 14 kg", en: "50 min tempo climb, 10% grade, 14 kg pack", es: "50 min de subida tempo, pendiente 10 %, mochila 14 kg")),
        "50 min montée tempo gradient 10% sac 17 kg": .freeText(LocalizedText(fr: "50 min de montée tempo, pente 10 %, sac 17 kg", en: "50 min tempo climb, 10% grade, 17 kg pack", es: "50 min de subida tempo, pendiente 10 %, mochila 17 kg")),
        "60 min montée tempo gradient 10-12% sac 13 kg": .freeText(LocalizedText(fr: "60 min de montée tempo, pente 10-12 %, sac 13 kg", en: "60 min tempo climb, 10-12% grade, 13 kg pack", es: "60 min de subida tempo, pendiente 10-12 %, mochila 13 kg")),
        "70 min montée tempo gradient 10-15% sac 14 kg": .freeText(LocalizedText(fr: "70 min de montée tempo, pente 10-15 %, sac 14 kg", en: "70 min tempo climb, 10-15% grade, 14 kg pack", es: "70 min de subida tempo, pendiente 10-15 %, mochila 14 kg")),
        "75 min montée tempo gradient 10-15% sac 15 kg": .freeText(LocalizedText(fr: "75 min de montée tempo, pente 10-15 %, sac 15 kg", en: "75 min tempo climb, 10-15% grade, 15 kg pack", es: "75 min de subida tempo, pendiente 10-15 %, mochila 15 kg")),
        "75 min montée tempo gradient 10-15% sac 18 kg": .freeText(LocalizedText(fr: "75 min de montée tempo, pente 10-15 %, sac 18 kg", en: "75 min tempo climb, 10-15% grade, 18 kg pack", es: "75 min de subida tempo, pendiente 10-15 %, mochila 18 kg")),
        "75 min montée tempo gradient 10-15% sac 20 kg": .freeText(LocalizedText(fr: "75 min de montée tempo, pente 10-15 %, sac 20 kg", en: "75 min tempo climb, 10-15% grade, 20 kg pack", es: "75 min de subida tempo, pendiente 10-15 %, mochila 20 kg")),
        "80 min montée tempo gradient 10-15% sac 16 kg": .freeText(LocalizedText(fr: "80 min de montée tempo, pente 10-15 %, sac 16 kg", en: "80 min tempo climb, 10-15% grade, 16 kg pack", es: "80 min de subida tempo, pendiente 10-15 %, mochila 16 kg")),
        "90 min montée tempo gradient 10-15% sac 18 kg": .freeText(LocalizedText(fr: "90 min de montée tempo, pente 10-15 %, sac 18 kg", en: "90 min tempo climb, 10-15% grade, 18 kg pack", es: "90 min de subida tempo, pendiente 10-15 %, mochila 18 kg")),
        "20 min montée gradient 5-8% endurance facile à tempo": .freeText(LocalizedText(fr: "20 min de montée, pente 5-8 %, endurance facile à tempo", en: "20 min climb, 5-8% grade, easy endurance to tempo", es: "20 min de subida, pendiente 5-8 %, resistencia suave a tempo")),
        "15 min descente technique": .freeText(LocalizedText(fr: "15 min de descente technique", en: "15 min technical downhill", es: "15 min de bajada técnica")),
        "20 min descente": .freeText(LocalizedText(fr: "20 min de descente", en: "20 min downhill", es: "20 min de bajada")),
        "30 min marche plate très facile": .freeText(LocalizedText(fr: "30 min de marche plate très facile", en: "30 min flat walk, very easy", es: "30 min de caminata llana muy fácil")),
        "4 min montée RPE 6 + 3 min descente très facile": .freeText(LocalizedText(fr: "4 min de montée RPE 6 + 3 min de descente très facile", en: "4 min uphill RPE 6 + 3 min very easy downhill", es: "4 min de subida RPE 6 + 3 min de bajada muy fácil")),
        "5 min montée RPE 5-6 + 4 min descente très facile": .freeText(LocalizedText(fr: "5 min de montée RPE 5-6 + 4 min de descente très facile", en: "5 min uphill RPE 5-6 + 4 min very easy downhill", es: "5 min de subida RPE 5-6 + 4 min de bajada muy fácil")),
        "5 min montée RPE 6-7 + 4 min récup descente très facile": .freeText(LocalizedText(fr: "5 min de montée RPE 6-7 + 4 min de récup en descente très facile", en: "5 min uphill RPE 6-7 + 4 min recovery on very easy downhill", es: "5 min de subida RPE 6-7 + 4 min de recuperación en bajada muy fácil")),
        "6 min montée RPE 6-7 + 4 min récup descente très facile": .freeText(LocalizedText(fr: "6 min de montée RPE 6-7 + 4 min de récup en descente très facile", en: "6 min uphill RPE 6-7 + 4 min recovery on very easy downhill", es: "6 min de subida RPE 6-7 + 4 min de recuperación en bajada muy fácil")),
        "8 min montée RPE 6-7 + 5 min récup descente très facile": .freeText(LocalizedText(fr: "8 min de montée RPE 6-7 + 5 min de récup en descente très facile", en: "8 min uphill RPE 6-7 + 5 min recovery on very easy downhill", es: "8 min de subida RPE 6-7 + 5 min de recuperación en bajada muy fácil")),
        "5 min descente technique + 3 min remontée très facile": .freeText(LocalizedText(fr: "5 min de descente technique + 3 min de remontée très facile", en: "5 min technical downhill + 3 min very easy climb back", es: "5 min de bajada técnica + 3 min de resubida muy fácil")),
        "10 min montée RPE 8-9 gradient 15% sac 17 kg + 8 min descente très facile": .freeText(LocalizedText(fr: "10 min de montée RPE 8-9, pente 15 %, sac 17 kg + 8 min de descente très facile", en: "10 min uphill RPE 8-9, 15% grade, 17 kg pack + 8 min very easy downhill", es: "10 min de subida RPE 8-9, pendiente 15 %, mochila 17 kg + 8 min de bajada muy fácil")),
        "10 min montée RPE 8-9 gradient 15-18% sac 15 kg + 7 min descente très facile": .freeText(LocalizedText(fr: "10 min de montée RPE 8-9, pente 15-18 %, sac 15 kg + 7 min de descente très facile", en: "10 min uphill RPE 8-9, 15-18% grade, 15 kg pack + 7 min very easy downhill", es: "10 min de subida RPE 8-9, pendiente 15-18 %, mochila 15 kg + 7 min de bajada muy fácil")),
        "10 min montée RPE 8-9 gradient 15-20% sac 20 kg + 8 min descente très facile": .freeText(LocalizedText(fr: "10 min de montée RPE 8-9, pente 15-20 %, sac 20 kg + 8 min de descente très facile", en: "10 min uphill RPE 8-9, 15-20% grade, 20 kg pack + 8 min very easy downhill", es: "10 min de subida RPE 8-9, pendiente 15-20 %, mochila 20 kg + 8 min de bajada muy fácil")),
        "8 min montée RPE 8-9 gradient 15-18% sac 15 kg + 8 min descente très facile récup": .freeText(LocalizedText(fr: "8 min de montée RPE 8-9, pente 15-18 %, sac 15 kg + 8 min de descente très facile en récup", en: "8 min uphill RPE 8-9, 15-18% grade, 15 kg pack + 8 min very easy downhill recovery", es: "8 min de subida RPE 8-9, pendiente 15-18 %, mochila 15 kg + 8 min de bajada muy fácil en recuperación")),
        "6 min montée tempo gradient 8-12% + 4 min descente très facile récup": .freeText(LocalizedText(fr: "6 min de montée tempo, pente 8-12 % + 4 min de descente très facile en récup", en: "6 min tempo climb, 8-12% grade + 4 min very easy downhill recovery", es: "6 min de subida tempo, pendiente 8-12 % + 4 min de bajada muy fácil en recuperación")),
        "6 min montée tempo gradient 8-12% sac 11 kg + 4 min descente très facile": .freeText(LocalizedText(fr: "6 min de montée tempo, pente 8-12 %, sac 11 kg + 4 min de descente très facile", en: "6 min tempo climb, 8-12% grade, 11 kg pack + 4 min very easy downhill", es: "6 min de subida tempo, pendiente 8-12 %, mochila 11 kg + 4 min de bajada muy fácil")),
        "8 min montée tempo gradient 8-12% sac 11 kg + 5 min descente très facile": .freeText(LocalizedText(fr: "8 min de montée tempo, pente 8-12 %, sac 11 kg + 5 min de descente très facile", en: "8 min tempo climb, 8-12% grade, 11 kg pack + 5 min very easy downhill", es: "8 min de subida tempo, pendiente 8-12 %, mochila 11 kg + 5 min de bajada muy fácil")),
        "8 min montée tempo gradient 10-12% sac 12 kg + 5 min descente très facile": .freeText(LocalizedText(fr: "8 min de montée tempo, pente 10-12 %, sac 12 kg + 5 min de descente très facile", en: "8 min tempo climb, 10-12% grade, 12 kg pack + 5 min very easy downhill", es: "8 min de subida tempo, pendiente 10-12 %, mochila 12 kg + 5 min de bajada muy fácil")),
        "8 min montée tempo gradient 10-12% sac 13 kg + 5 min descente très facile": .freeText(LocalizedText(fr: "8 min de montée tempo, pente 10-12 %, sac 13 kg + 5 min de descente très facile", en: "8 min tempo climb, 10-12% grade, 13 kg pack + 5 min very easy downhill", es: "8 min de subida tempo, pendiente 10-12 %, mochila 13 kg + 5 min de bajada muy fácil")),
        "16": .structured(StructuredDose(value: "16", unit: DoseUnit(rawValue: "reps")!)),
        "18": .structured(StructuredDose(value: "18", unit: DoseUnit(rawValue: "reps")!)),
        "5 par série": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSet")!)),
        "6 par série": .structured(StructuredDose(value: "6", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSet")!)),
        "8 par série": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSet")!)),
        "10 par série": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSet")!)),
        "12 par série": .structured(StructuredDose(value: "12", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSet")!)),
        "8 par lettre": .structured(StructuredDose(value: "8", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLetter")!)),
        "14 par jambe": .structured(StructuredDose(value: "14", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "8-10 par jambe": .structured(StructuredDose(value: "8-10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "30 sec par jambe": .structured(StructuredDose(value: "30", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "35 sec par jambe": .structured(StructuredDose(value: "35", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "40 sec par jambe": .structured(StructuredDose(value: "40", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perLeg")!)),
        "40 sec par côté": .structured(StructuredDose(value: "40", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "10 lifts par côté": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "12 par côté + 60 sec planche": .freeText(LocalizedText(fr: "12 par côté + 60 s de planche", en: "12 per side + 60 s plank", es: "12 por lado + 60 s de plancha")),
        "60 sec planche + 12 Pallof/côté": .freeText(LocalizedText(fr: "60 s de planche + 12 Pallof par côté", en: "60 s plank + 12 Pallof per side", es: "60 s de plancha + 12 Pallof por lado")),
        "60 sec planche + 45 sec/côté": .freeText(LocalizedText(fr: "60 s de planche + 45 s par côté", en: "60 s plank + 45 s per side", es: "60 s de plancha + 45 s por lado")),
        // ====================== LOT 6 — HIIT (généré, ne pas éditer) ======================
        "20 sec work + 10 sec rest": .interval([IntervalSegment(value: "20", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "work")!), IntervalSegment(value: "10", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "rest")!)]),
        "30 sec work + 30 sec rest": .interval([IntervalSegment(value: "30", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "work")!), IntervalSegment(value: "30", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "rest")!)]),
        "30 sec work + 60 sec rest": .interval([IntervalSegment(value: "30", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "work")!), IntervalSegment(value: "60", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "rest")!)]),
        "40 sec work + 20 sec rest": .interval([IntervalSegment(value: "40", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "work")!), IntervalSegment(value: "20", unit: DoseUnit(rawValue: "seconds")!, activity: DoseActivity(rawValue: "rest")!)]),
        "1 min par round": .structured(StructuredDose(value: "1", unit: DoseUnit(rawValue: "minutes")!, qualifier: DoseQualifier(rawValue: "perRound")!)),
        "1 min par round (work + repos auto-régulé)": .freeText(LocalizedText(fr: "1 min par round (effort + repos auto-géré)", en: "1 min per round (work + self-paced rest)", es: "1 min por ronda (trabajo + descanso autorregulado)")),
        "10 min par bloc": .freeText(LocalizedText(fr: "10 min par bloc", en: "10 min per block", es: "10 min por bloque")),
        "120 sec": .structured(StructuredDose(value: "120", unit: DoseUnit(rawValue: "seconds")!)),
        "180 sec": .structured(StructuredDose(value: "180", unit: DoseUnit(rawValue: "seconds")!)),
        "240 sec": .structured(StructuredDose(value: "240", unit: DoseUnit(rawValue: "seconds")!)),
        "300 sec": .structured(StructuredDose(value: "300", unit: DoseUnit(rawValue: "seconds")!)),
        "3": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "reps")!)),
        "4": .structured(StructuredDose(value: "4", unit: DoseUnit(rawValue: "reps")!)),
        "3 par côté": .structured(StructuredDose(value: "3", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "10 par bras": .structured(StructuredDose(value: "10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perArm")!)),
        "5 par bras": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perArm")!)),
        "1 min lecture avant séance": .freeText(LocalizedText(fr: "1 min de lecture avant la séance", en: "1 min reading before the session", es: "1 min de lectura antes de la sesión")),
        "20 m par push": .freeText(LocalizedText(fr: "20 m par poussée", en: "20 m per push", es: "20 m por empuje")),
        "20 m sled + 20 m farmer carry": .freeText(LocalizedText(fr: "20 m de sled + 20 m de farmer carry", en: "20 m sled + 20 m farmer carry", es: "20 m de sled + 20 m de farmer carry")),
        "12 calf/jambe + 15 tibialis/jambe": .freeText(LocalizedText(fr: "12 calf par jambe + 15 tibialis par jambe", en: "12 calf per leg + 15 tibialis per leg", es: "12 calf por pierna + 15 tibialis por pierna")),
        "12 calf/jambe + 15 tibialis/jambe + 12 scapular": .freeText(LocalizedText(fr: "12 calf par jambe + 15 tibialis par jambe + 12 scapular", en: "12 calf per leg + 15 tibialis per leg + 12 scapular", es: "12 calf por pierna + 15 tibialis por pierna + 12 scapular")),
        "15 calf/jambe + 18 tibialis/jambe": .freeText(LocalizedText(fr: "15 calf par jambe + 18 tibialis par jambe", en: "15 calf per leg + 18 tibialis per leg", es: "15 calf por pierna + 18 tibialis por pierna")),
        "12 scapular + 12 Y-raise": .freeText(LocalizedText(fr: "12 scapular + 12 Y-raise", en: "12 scapular + 12 Y-raise", es: "12 scapular + 12 Y-raise")),
        "12 Y + 12 face pull": .freeText(LocalizedText(fr: "12 Y + 12 face pull", en: "12 Y + 12 face pull", es: "12 Y + 12 face pull")),
        "15 tibialis + 12 scapular pull-up": .freeText(LocalizedText(fr: "15 tibialis + 12 scapular pull-up", en: "15 tibialis + 12 scapular pull-up", es: "15 tibialis + 12 scapular pull-up")),
        "12 squat + 8 push-up genoux": .freeText(LocalizedText(fr: "12 squats + 8 push-up sur genoux", en: "12 squats + 8 knee push-ups", es: "12 squats + 8 push-up de rodillas")),
        "30 sec dead bug + 30 sec bird dog": .freeText(LocalizedText(fr: "30 s de dead bug + 30 s de bird dog", en: "30 s dead bug + 30 s bird dog", es: "30 s de dead bug + 30 s de bird dog")),
        "30 sec hollow + 30 sec V-ups": .freeText(LocalizedText(fr: "30 s de hollow + 30 s de V-ups", en: "30 s hollow + 30 s V-ups", es: "30 s de hollow + 30 s de V-ups")),
        "30 sec hollow rocks + 30 sec V-ups": .freeText(LocalizedText(fr: "30 s de hollow rocks + 30 s de V-ups", en: "30 s hollow rocks + 30 s V-ups", es: "30 s de hollow rocks + 30 s de V-ups")),
        "30 sec hollow rocks + 30 sec dead bug": .freeText(LocalizedText(fr: "30 s de hollow rocks + 30 s de dead bug", en: "30 s hollow rocks + 30 s dead bug", es: "30 s de hollow rocks + 30 s de dead bug")),
        "30 sec ventrale + 20 sec latérale/côté": .freeText(LocalizedText(fr: "30 s de planche ventrale + 20 s de planche latérale par côté", en: "30 s front plank + 20 s side plank per side", es: "30 s de plancha frontal + 20 s de plancha lateral por lado")),
        "45 sec ventrale + 30 sec latérale/côté": .freeText(LocalizedText(fr: "45 s de planche ventrale + 30 s de planche latérale par côté", en: "45 s front plank + 30 s side plank per side", es: "45 s de plancha frontal + 30 s de plancha lateral por lado")),
        "60 sec ventrale + 30 sec latérale/côté": .freeText(LocalizedText(fr: "60 s de planche ventrale + 30 s de planche latérale par côté", en: "60 s front plank + 30 s side plank per side", es: "60 s de plancha frontal + 30 s de plancha lateral por lado")),
        "60 sec ventrale + 45 sec latérale/côté": .freeText(LocalizedText(fr: "60 s de planche ventrale + 45 s de planche latérale par côté", en: "60 s front plank + 45 s side plank per side", es: "60 s de plancha frontal + 45 s de plancha lateral por lado")),
        "45 sec planche + 30 sec dead bug + 30 sec bird dog": .freeText(LocalizedText(fr: "45 s de planche + 30 s de dead bug + 30 s de bird dog", en: "45 s plank + 30 s dead bug + 30 s bird dog", es: "45 s de plancha + 30 s de dead bug + 30 s de bird dog")),
        "45 sec planche + 30 sec dead bug/côté": .freeText(LocalizedText(fr: "45 s de planche + 30 s de dead bug par côté", en: "45 s plank + 30 s dead bug per side", es: "45 s de plancha + 30 s de dead bug por lado")),
        "45 sec planche + 30 sec side plank/côté": .freeText(LocalizedText(fr: "45 s de planche + 30 s de planche latérale par côté", en: "45 s plank + 30 s side plank per side", es: "45 s de plancha + 30 s de plancha lateral por lado")),
        "45 sec planche + 30 sec side/côté + 30 sec dead bug": .freeText(LocalizedText(fr: "45 s de planche + 30 s de planche latérale par côté + 30 s de dead bug", en: "45 s plank + 30 s side plank per side + 30 s dead bug", es: "45 s de plancha + 30 s de plancha lateral por lado + 30 s de dead bug")),
        "50 sec planche + 30 sec side plank/côté": .freeText(LocalizedText(fr: "50 s de planche + 30 s de planche latérale par côté", en: "50 s plank + 30 s side plank per side", es: "50 s de plancha + 30 s de plancha lateral por lado")),
        "60 sec planche + 30 sec dead bug/côté": .freeText(LocalizedText(fr: "60 s de planche + 30 s de dead bug par côté", en: "60 s plank + 30 s dead bug per side", es: "60 s de plancha + 30 s de dead bug por lado")),
        "60 sec planche + 30 sec side/côté": .freeText(LocalizedText(fr: "60 s de planche + 30 s de planche latérale par côté", en: "60 s plank + 30 s side plank per side", es: "60 s de plancha + 30 s de plancha lateral por lado")),
        "60 sec planche + 35 sec side plank/côté": .freeText(LocalizedText(fr: "60 s de planche + 35 s de planche latérale par côté", en: "60 s plank + 35 s side plank per side", es: "60 s de plancha + 35 s de plancha lateral por lado")),
        "60 sec planche + 40 sec side plank/côté": .freeText(LocalizedText(fr: "60 s de planche + 40 s de planche latérale par côté", en: "60 s plank + 40 s side plank per side", es: "60 s de plancha + 40 s de plancha lateral por lado")),
        "75 sec planche + 30 sec dead bug/côté": .freeText(LocalizedText(fr: "75 s de planche + 30 s de dead bug par côté", en: "75 s plank + 30 s dead bug per side", es: "75 s de plancha + 30 s de dead bug por lado")),
        "75 sec planche + 45 sec side/côté": .freeText(LocalizedText(fr: "75 s de planche + 45 s de planche latérale par côté", en: "75 s plank + 45 s side plank per side", es: "75 s de plancha + 45 s de plancha lateral por lado")),
        "75 sec planche + 45 sec side/côté + 12 dead bug/côté": .freeText(LocalizedText(fr: "75 s de planche + 45 s de planche latérale par côté + 12 dead bug par côté", en: "75 s plank + 45 s side plank per side + 12 dead bug per side", es: "75 s de plancha + 45 s de plancha lateral por lado + 12 dead bug por lado")),
        "90 sec planche + 30 sec dead bug/côté": .freeText(LocalizedText(fr: "90 s de planche + 30 s de dead bug par côté", en: "90 s plank + 30 s dead bug per side", es: "90 s de plancha + 30 s de dead bug por lado")),
        "90 sec planche + 45 sec side/côté + 15 dead bug/côté": .freeText(LocalizedText(fr: "90 s de planche + 45 s de planche latérale par côté + 15 dead bug par côté", en: "90 s plank + 45 s side plank per side + 15 dead bug per side", es: "90 s de plancha + 45 s de plancha lateral por lado + 15 dead bug por lado")),
        "15 reps tibialis + 60 sec planche + 30 sec side/côté": .freeText(LocalizedText(fr: "15 tibialis + 60 s de planche + 30 s de planche latérale par côté", en: "15 tibialis + 60 s plank + 30 s side plank per side", es: "15 tibialis + 60 s de plancha + 30 s de plancha lateral por lado")),
        "15 tibialis/jambe + 60 sec planche": .freeText(LocalizedText(fr: "15 tibialis par jambe + 60 s de planche", en: "15 tibialis per leg + 60 s plank", es: "15 tibialis por pierna + 60 s de plancha")),
        "15 tibialis/jambe + 60 sec planche + 30 sec side/côté": .freeText(LocalizedText(fr: "15 tibialis par jambe + 60 s de planche + 30 s de planche latérale par côté", en: "15 tibialis per leg + 60 s plank + 30 s side plank per side", es: "15 tibialis por pierna + 60 s de plancha + 30 s de plancha lateral por lado")),
        "10 hip thrust + 30 sec copenhagen/côté": .freeText(LocalizedText(fr: "10 hip thrust + 30 s de copenhagen par côté", en: "10 hip thrust + 30 s copenhagen per side", es: "10 hip thrust + 30 s de copenhagen por lado")),
        "5 Nordic + 8 split squat/jambe DB 12 kg": .freeText(LocalizedText(fr: "5 Nordic + 8 split squat par jambe, haltères 12 kg", en: "5 Nordic + 8 split squat per leg, 12 kg dumbbells", es: "5 Nordic + 8 split squat por pierna, mancuernas 12 kg")),
        "5 Nordic + 8 split squat/jambe DB 14 kg": .freeText(LocalizedText(fr: "5 Nordic + 8 split squat par jambe, haltères 14 kg", en: "5 Nordic + 8 split squat per leg, 14 kg dumbbells", es: "5 Nordic + 8 split squat por pierna, mancuernas 14 kg")),
        // ====================== LOT 7 — STRENGTH (généré, ne pas éditer) ======================
        "8-10": .structured(StructuredDose(value: "8-10", unit: DoseUnit(rawValue: "reps")!)),
        "8-12": .structured(StructuredDose(value: "8-12", unit: DoseUnit(rawValue: "reps")!)),
        "10-12": .structured(StructuredDose(value: "10-12", unit: DoseUnit(rawValue: "reps")!)),
        "10-15": .structured(StructuredDose(value: "10-15", unit: DoseUnit(rawValue: "reps")!)),
        "12-15": .structured(StructuredDose(value: "12-15", unit: DoseUnit(rawValue: "reps")!)),
        "6-10": .structured(StructuredDose(value: "6-10", unit: DoseUnit(rawValue: "reps")!)),
        "4-5": .structured(StructuredDose(value: "4-5", unit: DoseUnit(rawValue: "reps")!)),
        "3-5": .structured(StructuredDose(value: "3-5", unit: DoseUnit(rawValue: "reps")!)),
        "8-10 par côté": .structured(StructuredDose(value: "8-10", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "5 par épaule": .structured(StructuredDose(value: "5", unit: DoseUnit(rawValue: "reps")!, qualifier: DoseQualifier(rawValue: "perShoulder")!)),
        "75 sec": .structured(StructuredDose(value: "75", unit: DoseUnit(rawValue: "seconds")!)),
        "50 sec par côté": .structured(StructuredDose(value: "50", unit: DoseUnit(rawValue: "seconds")!, qualifier: DoseQualifier(rawValue: "perSide")!)),
        "5,6,8,8": .freeText(LocalizedText(fr: "5, 6, 8, 8", en: "5, 6, 8, 8", es: "5, 6, 8, 8")),
        "3,5,6,6": .freeText(LocalizedText(fr: "3, 5, 6, 6", en: "3, 5, 6, 6", es: "3, 5, 6, 6")),
        "5, 5, 5, 5+ AMRAP": .freeText(LocalizedText(fr: "5, 5, 5, 5+ AMRAP", en: "5, 5, 5, 5+ AMRAP", es: "5, 5, 5, 5+ AMRAP")),
        "5, 3, 1+ AMRAP": .freeText(LocalizedText(fr: "5, 3, 1+ AMRAP", en: "5, 3, 1+ AMRAP", es: "5, 3, 1+ AMRAP")),
        "3, 3, 3, 3+ AMRAP": .freeText(LocalizedText(fr: "3, 3, 3, 3+ AMRAP", en: "3, 3, 3, 3+ AMRAP", es: "3, 3, 3, 3+ AMRAP")),
        "5,6,8,AMRAP": .freeText(LocalizedText(fr: "5, 6, 8, AMRAP", en: "5, 6, 8, AMRAP", es: "5, 6, 8, AMRAP")),
        "3,5,6,AMRAP": .freeText(LocalizedText(fr: "3, 5, 6, AMRAP", en: "3, 5, 6, AMRAP", es: "3, 5, 6, AMRAP")),
        "AMRAP 1 set": .freeText(LocalizedText(fr: "AMRAP — 1 série", en: "AMRAP — 1 set", es: "AMRAP — 1 serie")),
        "1 (3 attempts max)": .freeText(LocalizedText(fr: "1 (3 essais max)", en: "1 (3 attempts max)", es: "1 (3 intentos máx.)")),
        "max": .freeText(LocalizedText(fr: "max", en: "max", es: "máx.")),
        "max propre": .freeText(LocalizedText(fr: "max propre", en: "clean max", es: "máx. limpias")),
        "8 de chaque exercice": .freeText(LocalizedText(fr: "8 de chaque exercice", en: "8 of each exercise", es: "8 de cada ejercicio")),
        "10 de chaque exercice": .freeText(LocalizedText(fr: "10 de chaque exercice", en: "10 of each exercise", es: "10 de cada ejercicio")),
    ]
}
