import Foundation

struct TemplateSpec {
    let id: String
    let sport: String
    let level: String
    let name: String
    let durationWeeks: Int
    let sessionsPerWeek: Int
    let defaultObjective: String
    let assumedProfile: String
}

enum TemplateMatrix {
    /// Les 38 templates visés par Epic 0.5 (10 sports × 4 niveaux moins les 2 cases incohérentes :
    /// triathlon débutant et remise-en-forme expert).
    static let all: [TemplateSpec] = [
        // --- Running (4)
        .init(id: "running-debutant-5k-8sem", sport: "running", level: "debutant",
              name: "5K Doux — 8 semaines pour courir 30 min en continu",
              durationWeeks: 8, sessionsPerWeek: 3,
              defaultObjective: "Courir 30 minutes en continu (équivalent 5K à allure débutante confortable)",
              assumedProfile: "Adulte sédentaire ou peu actif, sans pathologie cardiaque, chaussures running amorties en bon état. Aucune pratique récente. Capable de marcher 30 min sans pause."),
        .init(id: "running-intermediaire-10k-8sem", sport: "running", level: "intermediaire",
              name: "10K — 8 semaines pour franchir la barre des 10 km",
              durationWeeks: 8, sessionsPerWeek: 3,
              defaultObjective: "Courir 10 km en continu (objectif de temps libre, typiquement 55-70 min)",
              assumedProfile: "Coureur régulier capable de courir 5 km en 30-35 min sans difficulté, pratique 2×/semaine depuis au moins 2 mois. Aucune blessure active."),
        .init(id: "running-avance-semi-marathon-12sem", sport: "running", level: "avance",
              name: "Semi-marathon — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 4,
              defaultObjective: "Terminer un semi-marathon (21,1 km) en continu, objectif de temps personnel",
              assumedProfile: "Coureur confirmé capable de tenir 10 km en 50-60 min, pratique régulière 3×/sem depuis 6 mois minimum. Familier du seuil aérobie et des sorties longues."),
        .init(id: "running-expert-marathon-16sem", sport: "running", level: "expert",
              name: "Marathon — 16 semaines",
              durationWeeks: 16, sessionsPerWeek: 5,
              defaultObjective: "Terminer un marathon (42,2 km), cible de temps personnel",
              assumedProfile: "Coureur expérimenté ayant déjà couru au moins un semi-marathon, pratique hebdo 40+ km, connaissance de sa FC seuil et de son allure marathon cible."),

        // --- Musculation (4)
        .init(id: "musculation-debutant-home-basics-8sem", sport: "musculation", level: "debutant",
              name: "Musculation maison — Fondamentaux en 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 3,
              defaultObjective: "Acquérir les mouvements de base (squat, pompe, tirage, gainage) et construire l'habitude d'un entraînement régulier",
              assumedProfile: "Adulte sédentaire sans expérience musculation récente, équipé d'une paire d'haltères ajustables (2 à 15 kg), d'un tapis, et d'un espace de 2×2 m. Pas de banc, pas de barre."),
        .init(id: "musculation-intermediaire-upperlower-12sem", sport: "musculation", level: "intermediaire",
              name: "Split Upper/Lower — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 4,
              defaultObjective: "Développer la force et l'hypertrophie générale via un split haut/bas structuré en 4 séances/semaine",
              assumedProfile: "Pratiquant régulier depuis 6+ mois, accès salle de sport complète (rack, banc, barres, haltères, machines). Maîtrise technique du squat, deadlift, bench press."),
        .init(id: "musculation-avance-ppl-12sem", sport: "musculation", level: "avance",
              name: "Push-Pull-Legs — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 6,
              defaultObjective: "Maximiser le volume et la fréquence par groupe musculaire via un split PPL 6 séances/semaine pour hypertrophie avancée",
              assumedProfile: "Pratiquant avancé avec 2+ ans d'expérience, maîtrise des mouvements composés, salle complète. Capable d'encaisser 6 séances/semaine avec nutrition adaptée."),
        .init(id: "musculation-expert-strength-5x5-cycle", sport: "musculation", level: "expert",
              name: "Force 5×5 — Cycle de progression",
              durationWeeks: 12, sessionsPerWeek: 3,
              defaultObjective: "Progresser en force pure sur squat, bench press, deadlift, overhead press, rowing selon protocole 5×5 progressif",
              assumedProfile: "Pratiquant expert avec 3+ ans de musculation, force maximale connue sur les mouvements composés. Accès salle complète avec plateau et plaques fractionnées."),

        // --- Natation (4)
        .init(id: "natation-debutant-initiation-6sem", sport: "natation", level: "debutant",
              name: "Natation initiation — Nager 200 m en 6 semaines",
              durationWeeks: 6, sessionsPerWeek: 2,
              defaultObjective: "Nager 200 m en crawl sans s'arrêter, avec une respiration latérale maîtrisée",
              assumedProfile: "Adulte à l'aise dans l'eau et sachant flotter, accès à une piscine 25 m, aucune pratique régulière de la natation sportive. Maillot + lunettes + bonnet disponibles."),
        .init(id: "natation-intermediaire-endurance-8sem", sport: "natation", level: "intermediaire",
              name: "Natation endurance — 1000 m continu en 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 2,
              defaultObjective: "Nager 1000 m en crawl sans pause, à une allure régulière",
              assumedProfile: "Nageur capable de nager 200-400 m en continu, pratique 1×/sem depuis quelques mois. Respiration latérale acquise, technique crawl perfectible."),
        .init(id: "natation-avance-technique-8sem", sport: "natation", level: "avance",
              name: "Natation technique — Perfectionnement sur 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 3,
              defaultObjective: "Améliorer l'efficience du crawl (glisse, respiration bilatérale, pull) et intégrer brasse et dos pour la variété",
              assumedProfile: "Nageur confirmé tenant 1500-2000 m en continu, respiration bilatérale acquise, souhaite perfectionner la technique avant d'envisager distances longues ou triathlon."),
        .init(id: "natation-expert-perfectionnement-12sem", sport: "natation", level: "expert",
              name: "Natation perfectionnement — 12 semaines haute intensité",
              durationWeeks: 12, sessionsPerWeek: 4,
              defaultObjective: "Développer la vitesse (100 m, 200 m) et l'endurance spécifique (plus de 3000 m/séance) via un travail par séries rigoureux",
              assumedProfile: "Nageur expert ayant une pratique régulière 3+×/sem, à l'aise sur toutes les nages, connaissance des allures seuil/VO2max. Accès piscine avec couloirs libres."),

        // --- Vélo route (4)
        .init(id: "velo-debutant-reprise-6sem", sport: "velo", level: "debutant",
              name: "Vélo reprise — Retrouver le plaisir en 6 semaines",
              durationWeeks: 6, sessionsPerWeek: 2,
              defaultObjective: "Tenir 1h30 de vélo continu sur plat ou vallonné léger à allure confortable",
              assumedProfile: "Adulte ayant fait du vélo dans le passé mais arrêté depuis plusieurs mois/années, vélo en état de marche (route ou VTC), pas de soucis mécaniques ni lombaires."),
        .init(id: "velo-intermediaire-endurance-10sem", sport: "velo", level: "intermediaire",
              name: "Vélo endurance — 80 km en 10 semaines",
              durationWeeks: 10, sessionsPerWeek: 3,
              defaultObjective: "Couvrir 80 km en une seule sortie à allure endurance",
              assumedProfile: "Cycliste régulier tenant 40 km à 25-28 km/h, pratique 1-2×/sem, vélo de route avec cardio-fréquencemètre conseillé."),
        .init(id: "velo-avance-sorties-longues-12sem", sport: "velo", level: "avance",
              name: "Vélo sorties longues — 150 km en 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 4,
              defaultObjective: "Préparer une cyclosportive de 100-150 km avec dénivelé modéré",
              assumedProfile: "Cycliste confirmé sortant 2-3×/sem, tenant 80 km en 3h, connaissance des zones de puissance/FC, nutrition longue distance maîtrisée."),
        .init(id: "velo-expert-cyclosportive-16sem", sport: "velo", level: "expert",
              name: "Cyclosportive — Préparation 16 semaines",
              durationWeeks: 16, sessionsPerWeek: 5,
              defaultObjective: "Préparer une cyclosportive exigeante (180-220 km, 3000+ m de dénivelé) avec objectif de temps",
              assumedProfile: "Cycliste expert, base hebdo de 200+ km, maîtrise du pacing cols, capteur de puissance idéalement, nutrition/hydratation élaborées."),

        // --- Triathlon (3, pas de débutant)
        .init(id: "triathlon-intermediaire-sprint-12sem", sport: "triathlon", level: "intermediaire",
              name: "Triathlon Sprint — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 6,
              defaultObjective: "Terminer un triathlon sprint (750 m natation + 20 km vélo + 5 km course) avec transitions maîtrisées",
              assumedProfile: "Triathlète novice : capable de courir 5 km, nager 400 m en crawl et rouler 40 km séparément. Veut enchaîner pour la première fois."),
        .init(id: "triathlon-avance-distance-m-16sem", sport: "triathlon", level: "avance",
              name: "Triathlon Distance M (Olympique) — 16 semaines",
              durationWeeks: 16, sessionsPerWeek: 7,
              defaultObjective: "Terminer un triathlon distance M (1500 m natation + 40 km vélo + 10 km course) avec une stratégie d'allure",
              assumedProfile: "Triathlète ayant déjà terminé au moins un Sprint, pratique régulière 4-5 séances/sem, nage 1000 m en continu, roule 40 km régulièrement."),
        .init(id: "triathlon-expert-half-ironman-20sem", sport: "triathlon", level: "expert",
              name: "Half Ironman (70.3) — 20 semaines",
              durationWeeks: 20, sessionsPerWeek: 7,
              defaultObjective: "Terminer un triathlon Half Ironman (1,9 km natation + 90 km vélo + 21,1 km course)",
              assumedProfile: "Triathlète expert ayant fini au moins un Distance M, volume hebdo 10+ h, nage 2 km en continu, roule 90+ km, court semi-marathon. Doubles séances (AM/PM) possibles sur certains jours — à organiser par l'utilisateur selon son planning."),

        // --- Tennis (4)
        .init(id: "tennis-debutant-initiation-8sem", sport: "tennis", level: "debutant",
              name: "Tennis initiation — Premiers échanges en 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 2,
              defaultObjective: "Réaliser des échanges suivis fond de court (coup droit + revers) et tenir un point simple au service",
              assumedProfile: "Adulte sans expérience tennis, accès à un club ou court, équipement basique (raquette + balles). Bonne condition générale mais pas forcément sportive."),
        .init(id: "tennis-intermediaire-regularite-10sem", sport: "tennis", level: "intermediaire",
              name: "Tennis régularité — 10 semaines",
              durationWeeks: 10, sessionsPerWeek: 2,
              defaultObjective: "Améliorer la régularité fond de court (30+ échanges consécutifs), stabiliser service et retour, intégrer montée au filet",
              assumedProfile: "Joueur pratiquant 1×/sem depuis 6+ mois, maîtrise les fondamentaux, coup droit et revers acquis mais manque de régularité. Accès court régulier."),
        .init(id: "tennis-avance-match-prep-12sem", sport: "tennis", level: "avance",
              name: "Tennis match prep — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 3,
              defaultObjective: "Préparer des matchs en simple : tactique, service-volée, variations d'allure, gestion de la fatigue sur 2h",
              assumedProfile: "Joueur classé (30-15 à 15/5) pratiquant 2+×/sem, tous les coups maîtrisés, recherche compétition club ou tournois."),
        .init(id: "tennis-expert-tournoi-prep-16sem", sport: "tennis", level: "expert",
              name: "Tennis tournoi prep — 16 semaines",
              durationWeeks: 16, sessionsPerWeek: 4,
              defaultObjective: "Préparer un tournoi compétitif (classement 15 et mieux) avec pic de forme ciblé",
              assumedProfile: "Joueur 15 à seconde série, volume hebdo 6+h, coach ou partenaires réguliers de niveau équivalent, préparation physique dédiée."),

        // --- Yoga / Mobilité (4)
        .init(id: "yoga-debutant-initiation-6sem", sport: "yoga", level: "debutant",
              name: "Yoga initiation — 6 semaines pour une pratique autonome",
              durationWeeks: 6, sessionsPerWeek: 3,
              defaultObjective: "Acquérir 20 postures de base et enchaîner une séance de 30 min en autonomie",
              assumedProfile: "Adulte sans expérience yoga, tapis disponible, 30 min à consacrer par séance, absence de blessure active. Raideur classique de sédentaire."),
        .init(id: "yoga-intermediaire-hatha-8sem", sport: "yoga", level: "intermediaire",
              name: "Hatha yoga — 8 semaines de pratique régulière",
              durationWeeks: 8, sessionsPerWeek: 4,
              defaultObjective: "Tenir une pratique Hatha de 45-60 min incluant Sun Salutations et postures d'équilibre",
              assumedProfile: "Pratique occasionnelle yoga depuis plusieurs mois, connaît les postures de base, veut structurer une pratique régulière. Souplesse et équilibre corrects."),
        .init(id: "yoga-avance-vinyasa-10sem", sport: "yoga", level: "avance",
              name: "Vinyasa yoga — 10 semaines dynamiques",
              durationWeeks: 10, sessionsPerWeek: 4,
              defaultObjective: "Enchaîner des séquences Vinyasa fluides de 60 min avec inversions et postures d'équilibre avancées",
              assumedProfile: "Pratique régulière 2+×/sem depuis un an, postures de base maîtrisées, Chaturanga et Downward Dog propres, bonne condition physique."),
        .init(id: "yoga-expert-advanced-12sem", sport: "yoga", level: "expert",
              name: "Advanced yoga practice — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 5,
              defaultObjective: "Intégrer inversions avancées (Sirsasana, Pincha), arm balances (Bakasana, Handstand) et back bends profonds dans la pratique quotidienne",
              assumedProfile: "Pratiquant expert 5+ ans, postures intermédiaires maîtrisées, souplesse et force avancées, accompagnement possible par un professeur certifié."),

        // --- HIIT / Fonctionnel (4)
        .init(id: "hiit-debutant-6sem", sport: "hiit", level: "debutant",
              name: "HIIT initiation — 6 semaines",
              durationWeeks: 6, sessionsPerWeek: 3,
              defaultObjective: "Réaliser une séance HIIT de 20 min (intervalles courts 20-30 s d'effort) sans équipement",
              assumedProfile: "Adulte en condition correcte, sans pathologie cardiaque, 20 min à consacrer par séance. Pas d'équipement requis, espace minimal."),
        .init(id: "hiit-intermediaire-8sem", sport: "hiit", level: "intermediaire",
              name: "HIIT intermédiaire — 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 4,
              defaultObjective: "Tenir des séances HIIT de 30-35 min incluant Tabata, AMRAP et intervalles 40/20",
              assumedProfile: "Habitué au HIIT ou cardio régulier depuis 3+ mois, tolère une FC max proche. Équipement minimal : tapis, éventuellement kettlebell."),
        .init(id: "hiit-avance-10sem", sport: "hiit", level: "avance",
              name: "HIIT avancé — 10 semaines",
              durationWeeks: 10, sessionsPerWeek: 5,
              defaultObjective: "Enchaîner des WODs de 45 min (AMRAP 20+ min, For Time, EMOM complexes) avec matériel varié",
              assumedProfile: "Pratiquant régulier CrossFit-style ou HIIT intense, maîtrise mouvements olympiques basiques, accès kettlebells/haltères/box."),
        .init(id: "hiit-expert-athletique-12sem", sport: "hiit", level: "expert",
              name: "Préparation athlétique HIIT — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 5,
              defaultObjective: "Développer puissance, endurance musculaire et capacité anaérobie pour compétition fonctionnelle (Hyrox, CrossFit local)",
              assumedProfile: "Athlète fonctionnel expert, 2+ ans de pratique intense, mouvements olympiques maîtrisés, accès salle/box complet."),

        // --- Remise en forme (3, pas d'expert)
        .init(id: "remise-en-forme-debutant-reprise-6sem", sport: "remise_en_forme", level: "debutant",
              name: "Remise en forme — Reprise douce 6 semaines",
              durationWeeks: 6, sessionsPerWeek: 3,
              defaultObjective: "Retrouver une base cardio (30 min de marche rapide continue) + mobilité générale + gainage élémentaire",
              assumedProfile: "Adulte sédentaire depuis plusieurs mois, aucun sport récent, pas de pathologie majeure. Envie de bouger sans viser un sport particulier."),
        .init(id: "remise-en-forme-intermediaire-maintien-8sem", sport: "remise_en_forme", level: "intermediaire",
              name: "Remise en forme maintien — 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 4,
              defaultObjective: "Construire une routine mixte cardio + renfo + mobilité pour maintenir forme générale",
              assumedProfile: "Pratique sportive modérée depuis quelques mois, souhaite structurer un mix cardio/renfo/mobilité sans spécialisation."),
        .init(id: "remise-en-forme-avance-performance-10sem", sport: "remise_en_forme", level: "avance",
              name: "Performance générale — 10 semaines",
              durationWeeks: 10, sessionsPerWeek: 5,
              defaultObjective: "Développer une condition physique athlétique polyvalente (force, cardio VO2max, mobilité) sans spécialisation",
              assumedProfile: "Pratiquant régulier polyvalent 3-4×/sem, cherche à structurer sa progression vs faire du aléatoire."),

        // --- Sports collectifs (4)
        .init(id: "sports-collectifs-debutant-prepa-physique-8sem", sport: "sports_collectifs", level: "debutant",
              name: "Prépa physique sports co — 8 semaines initiation",
              durationWeeks: 8, sessionsPerWeek: 3,
              defaultObjective: "Acquérir les bases physiques pour pratiquer sport collectif de loisir (foot, basket, volley, handball) : cardio, changements de direction, force générale",
              assumedProfile: "Adulte souhaitant reprendre sport co en loisir, condition physique moyenne, pas de pratique récente du sport cible."),
        .init(id: "sports-collectifs-intermediaire-prepa-saison-8sem", sport: "sports_collectifs", level: "intermediaire",
              name: "Prépa saison sports co — 8 semaines",
              durationWeeks: 8, sessionsPerWeek: 4,
              defaultObjective: "Préparer une saison en équipe amateur : endurance spécifique, puissance, agilité, résilience articulaire",
              assumedProfile: "Joueur amateur avec expérience, reprend après coupure estivale ou prépare saison, 2-3 entraînements équipe/sem ajoutés à ce plan."),
        .init(id: "sports-collectifs-avance-match-physique-10sem", sport: "sports_collectifs", level: "avance",
              name: "Performance match — 10 semaines",
              durationWeeks: 10, sessionsPerWeek: 5,
              defaultObjective: "Développer la capacité de répéter efforts intenses en match (sprints, duels, récupération entre actions)",
              assumedProfile: "Joueur confirmé niveau départemental-régional, entraînements équipe 2-3×/sem, souhaite compléter par prépa individuelle."),
        .init(id: "sports-collectifs-expert-elite-prep-12sem", sport: "sports_collectifs", level: "expert",
              name: "Elite prep sports co — 12 semaines",
              durationWeeks: 12, sessionsPerWeek: 5,
              defaultObjective: "Préparation physique de haut niveau pour compétition régionale+ : pic de forme ciblé, périodisation, prévention blessure",
              assumedProfile: "Joueur élite semi-pro/pro ou espoir, staff technique ou encadrement, 5+ h d'entraînement équipe/sem."),
    ]

    static func find(id: String) -> TemplateSpec? {
        all.first { $0.id == id }
    }
}
